## Zero-shot prediction of *BRCA1* variant effects with Evo 2

The human *BRCA1* gene encodes for a protein that repairs damaged DNA ([Moynahan et al., 1999](https://www.cell.com/molecular-cell/fulltext/S1097-2765%2800%2980202-6)). Certain variants of this gene have been associated with an increased risk of breast and ovarian cancers ([Miki et al., 1994](https://www.science.org/doi/10.1126/science.7545954?url_ver=Z39.88-2003&rfr_id=ori:rid:crossref.org&rfr_dat=cr_pub%20%200pubmed)). Using Evo 2, we can predict whether a particular single nucleotide variant (SNV) of the *BRCA1* gene is likely to be harmful to the protein's function, and thus potentially increase the risk of cancer for the patient with the genetic variant.

We start by loading a dataset from [Findlay et al. (2018)](https://www.nature.com/articles/s41586-018-0461-z), which contains experimentally measured function scores of 3,893 *BRCA1* SNVs. These function scores reflect the extent by which the genetic variant has disrupted the protein's function, with lower scores indicating greater disruption. In this dataset, the SNVs are classified into three categories based on their function scores: `LOF` (loss-of-function), `INT` (intermediate), and `FUNC` (functional). We start by reading in this dataset.

In [1]:
# Install dependencies
!pip install matplotlib pandas seaborn scikit-learn openpyxl

# Required imports
from Bio import SeqIO
import gzip
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
import seaborn as sns
from sklearn.metrics import roc_auc_score

# Set root path
os.chdir('../..')

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

In [2]:
brca1_df = pd.read_excel(
    os.path.join('notebooks', 'brca1', '41586_2018_461_MOESM3_ESM.xlsx'),
    header=2,
)
brca1_df = brca1_df[[
    'chromosome', 'position (hg19)', 'reference', 'alt', 'function.score.mean', 'func.class',
]]

brca1_df.head(10)

   chromosome  position (hg19) reference alt  function.score.mean func.class
0          17         41276135         T   G            -0.372611       FUNC
1          17         41276135         T   C            -0.045313       FUNC
2          17         41276135         T   A            -0.108254       FUNC
3          17         41276134         T   G            -0.277963       FUNC
4          17         41276134         T   C            -0.388414       FUNC
5          17         41276134         T   A            -0.280973       FUNC
6          17         41276133         C   T            -0.973683        INT
7          17         41276133         C   G            -0.373489       FUNC
8          17         41276133         C   A             0.006314       FUNC
9          17         41276132         A   T            -0.207552       FUNC

We then group the `FUNC` and `INT` classes of SNVs together into a single category (`FUNC/INT`).

In [3]:
# Rename columns
brca1_df.rename(columns={
    'chromosome': 'chrom',
    'position (hg19)': 'pos',
    'reference': 'ref',
    'alt': 'alt',
    'function.score.mean': 'score',
    'func.class': 'class',
}, inplace=True)

# Convert to two-class system
brca1_df['class'] = brca1_df['class'].replace(['FUNC', 'INT'], 'FUNC/INT')

brca1_df.head(10)

   chrom       pos ref alt     score     class
0     17  41276135   T   G -0.372611  FUNC/INT
1     17  41276135   T   C -0.045313  FUNC/INT
2     17  41276135   T   A -0.108254  FUNC/INT
3     17  41276134   T   G -0.277963  FUNC/INT
4     17  41276134   T   C -0.388414  FUNC/INT
5     17  41276134   T   A -0.280973  FUNC/INT
6     17  41276133   C   T -0.973683  FUNC/INT
7     17  41276133   C   G -0.373489  FUNC/INT
8     17  41276133   C   A  0.006314  FUNC/INT
9     17  41276132   A   T -0.207552  FUNC/INT

We build a function to parse the reference and variant sequences of a 8,192-bp window around the genomic position of each SNV, using the reference sequence of human chromosome 17 where *BRCA1* is located.

In [4]:
WINDOW_SIZE = 8192

# Read the reference genome sequence of chromosome 17
with gzip.open(os.path.join('notebooks', 'brca1', 'GRCh37.p13_chr17.fna.gz'), "rt") as handle:
    for record in SeqIO.parse(handle, "fasta"):
        seq_chr17 = str(record.seq)
        break

def parse_sequences(pos, ref, alt):
    """
    Parse reference and variant sequences from the reference genome sequence.
    """
    p = pos - 1 # Convert to 0-indexed position
    full_seq = seq_chr17

    ref_seq_start = max(0, p - WINDOW_SIZE//2)
    ref_seq_end = min(len(full_seq), p + WINDOW_SIZE//2)
    ref_seq = seq_chr17[ref_seq_start:ref_seq_end]
    snv_pos_in_ref = min(WINDOW_SIZE//2, p)
    var_seq = ref_seq[:snv_pos_in_ref] + alt + ref_seq[snv_pos_in_ref+1:]

    # Sanity checks
    assert len(var_seq) == len(ref_seq)
    assert ref_seq[snv_pos_in_ref] == ref
    assert var_seq[snv_pos_in_ref] == alt

    return ref_seq, var_seq

# Parse sequences for the first variant
row = brca1_df.iloc[0]
ref_seq, var_seq = parse_sequences(row['pos'], row['ref'], row['alt'])

print(row)
print('--')
print(f'Reference, SNV 0: ...{ref_seq[4082:4112]}...')
print(f'Variant, SNV 0:   ...{var_seq[4082:4112]}...')

chrom          17
pos      41276135
ref             T
alt             G
score   -0.372611
class    FUNC/INT
Name: 0, dtype: object
--
Reference, SNV 0: ...TGTTCCAATGAACTTTAACACATTAGAAAA...
Variant, SNV 0:   ...TGTTCCAATGAACTGTAACACATTAGAAAA...

Then, we load Evo 2 1B and score the likelihoods of the reference and variant sequences of each SNV. (Note: we use the smaller Evo 2 1B base model here as a quick demonstration, but we strongly recommend using the larger Evo 2 7B and 40B models for more accurate predictions.)

In [5]:
from evo2.models import Evo2

# Load model
model = Evo2('evo2_1b_base')

/usr/local/lib/python3.12/dist-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

[09/07/26 10:53:27] INFO     httpx - INFO - HTTP Request: GET                                       ]8;id=433934;file:///usr/local/lib/python3.12/dist-packages/httpx/_client.py\_client.py]8;;\:]8;id=242565;file:///usr/local/lib/python3.12/dist-packages/httpx/_client.py#1025\1025]8;;\
                             https://huggingface.co/api/models/arcinstitute/evo2_1b_base/revision/m
                             ain "HTTP/1.1 200 OK"

Fetching 4 files:   0%|                                         | 0/4 [00:00<?, ?it/s]

Fetching 4 files: 100%|███████████████████████████████| 4/4 [00:00<00:00, 2213.65it/s]

Found complete file in repo: evo2_1b_base.pt

                    INFO     StripedHyena - INFO - Initializing StripedHyena with config:              ]8;id=545242;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=905921;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#645\645]8;;\
                             {'model_name': 'shc-evo2-1b-8k-2T-v2', 'vocab_size': 512, 'hidden_size':
                             1920, 'num_filters': 1920, 'attn_layer_idxs': [3, 10, 17, 24],
                             'hcl_layer_idxs': [2, 6, 9, 13, 16, 20, 23], 'hcm_layer_idxs': [1, 5, 8,
                             12, 15, 19, 22], 'hcs_layer_idxs': [0, 4, 7, 11, 14, 18, 21],
                             'hcm_filter_length': 128, 'hcl_filter_groups': 1920, 'hcm_filter_groups':
                             128, 'hcs_filter_groups': 128, 'hcs_filter_length': 7, 'num_layers': 25,
                             'short_filter_length': 3, 'num_attention_heads': 15, 'short_filter_bias':
                             False, 'mlp_init_method': 'torch.nn.init.zeros_',
                             'mlp_output_init_method': 'torch.nn.init.zeros_', 'eps': 1e-06,
                             'state_size': 16, 'rotary_emb_base': 10000,
                             'make_vocab_size_divisible_by': 8, 'inner_size_multiple_of': 16,
                             'inner_mlp_size': 5120, 'log_intermediate_values': False, 'proj_groups':
                             1, 'hyena_filter_groups': 1, 'column_split_hyena': False, 'column_split':
                             True, 'interleave': True, 'evo2_style_activations': True,
                             'model_parallel_size': 1, 'pipe_parallel_size': 1, 'tie_embeddings':
                             True, 'mha_out_proj_bias': True, 'hyena_out_proj_bias': True,
                             'hyena_flip_x1x2': False, 'qkv_proj_bias': False,
                             'use_fp8_input_projections': True, 'max_seqlen': 8192, 'max_batch_size':
                             1, 'final_norm': True, 'use_flash_attn': True, 'use_flash_rmsnorm':
                             False, 'use_flash_depthwise': False, 'use_flashfft': False,
                             'use_laughing_hyena': False, 'inference_mode': True, 'tokenizer_type':
                             'CharLevelTokenizer', 'prefill_style': 'fft', 'mlp_activation': 'gelu',
                             'print_activations': False, 'Loader': <class 'yaml.loader.FullLoader'>}

                    INFO     StripedHyena - INFO - Initializing 25 blocks...                           ]8;id=693417;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=382922;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#678\678]8;;\

                    INFO     StripedHyena - INFO - Distributing across 1 GPUs, approximately 25 layers ]8;id=138763;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=315650;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#685\685]8;;\
                             per GPU

  0%|                                                          | 0/25 [00:00<?, ?it/s]

                    INFO     StripedHyena - INFO - Assigned layer_idx=0 to device='cuda:0'             ]8;id=984170;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=1874;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#703\703]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 0: 44260736               ]8;id=689189;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=386283;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#704\704]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=1 to device='cuda:0'             ]8;id=26306;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=741130;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#703\703]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 1: 44278144               ]8;id=409577;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=17550;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#704\704]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=2 to device='cuda:0'             ]8;id=342372;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=106842;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#703\703]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 2: 44323200               ]8;id=709767;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=457441;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#704\704]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=3 to device='cuda:0'             ]8;id=434326;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=317244;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#703\703]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 3: 44242560               ]8;id=794124;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=208678;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#704\704]8;;\

 16%|████████                                          | 4/25 [00:00<00:00, 21.06it/s]

                    INFO     StripedHyena - INFO - Assigned layer_idx=4 to device='cuda:0'             ]8;id=738573;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=979990;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#703\703]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 4: 44260736               ]8;id=389383;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=238627;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#704\704]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=5 to device='cuda:0'             ]8;id=879333;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=444613;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#703\703]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 5: 44278144               ]8;id=141738;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=256987;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#704\704]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=6 to device='cuda:0'             ]8;id=310803;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=983583;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#703\703]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 6: 44323200               ]8;id=998530;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=693440;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#704\704]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=7 to device='cuda:0'             ]8;id=610896;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=465196;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#703\703]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 7: 44260736               ]8;id=312584;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=244637;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#704\704]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=8 to device='cuda:0'             ]8;id=352091;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=872749;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#703\703]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 8: 44278144               ]8;id=478481;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=41738;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#704\704]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=9 to device='cuda:0'             ]8;id=584473;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=571041;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#703\703]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 9: 44323200               ]8;id=990769;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=748444;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#704\704]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=10 to device='cuda:0'            ]8;id=270477;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=205507;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#703\703]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 10: 44242560              ]8;id=958439;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=756133;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#704\704]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=11 to device='cuda:0'            ]8;id=543341;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=655823;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#703\703]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 11: 44260736              ]8;id=723172;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=812467;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#704\704]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=12 to device='cuda:0'            ]8;id=993419;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=856847;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#703\703]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 12: 44278144              ]8;id=878967;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=18171;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#704\704]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=13 to device='cuda:0'            ]8;id=893975;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=673326;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#703\703]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 13: 44323200              ]8;id=173921;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=404075;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#704\704]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=14 to device='cuda:0'            ]8;id=565672;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=450764;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#703\703]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 14: 44260736              ]8;id=225003;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=91751;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#704\704]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=15 to device='cuda:0'            ]8;id=422107;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=137644;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#703\703]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 15: 44278144              ]8;id=39020;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=937527;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#704\704]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=16 to device='cuda:0'            ]8;id=727695;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=424754;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#703\703]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 16: 44323200              ]8;id=730647;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=571980;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#704\704]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=17 to device='cuda:0'            ]8;id=793433;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=328189;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#703\703]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 17: 44242560              ]8;id=472204;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=43388;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#704\704]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=18 to device='cuda:0'            ]8;id=748581;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=99375;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#703\703]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 18: 44260736              ]8;id=339249;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=845933;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#704\704]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=19 to device='cuda:0'            ]8;id=780499;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=979619;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#703\703]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 19: 44278144              ]8;id=868788;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=994117;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#704\704]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=20 to device='cuda:0'            ]8;id=219916;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=290382;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#703\703]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 20: 44323200              ]8;id=449959;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=980995;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#704\704]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=21 to device='cuda:0'            ]8;id=873409;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=954709;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#703\703]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 21: 44260736              ]8;id=774845;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=859573;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#704\704]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=22 to device='cuda:0'            ]8;id=775256;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=557956;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#703\703]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 22: 44278144              ]8;id=74592;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=708016;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#704\704]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=23 to device='cuda:0'            ]8;id=23906;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=441240;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#703\703]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 23: 44323200              ]8;id=836781;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=955311;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#704\704]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=24 to device='cuda:0'            ]8;id=195647;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=90650;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#703\703]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 24: 44242560              ]8;id=640255;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=985971;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#704\704]8;;\

100%|█████████████████████████████████████████████████| 25/25 [00:00<00:00, 92.35it/s]

                    INFO     StripedHyena - INFO - Initialized model                                   ]8;id=258935;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=275442;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#723\723]8;;\

                    INFO     vortex.model.utils - INFO - Loading                                        ]8;id=212852;file:///usr/local/lib/python3.12/dist-packages/vortex/model/utils.py\utils.py]8;;\:]8;id=496426;file:///usr/local/lib/python3.12/dist-packages/vortex/model/utils.py#92\92]8;;\
                             /root/.cache/huggingface/hub/models--arcinstitute--evo2_1b_base/snapshots/
                             2279e1df422c991037470302360edd40d0d2ea1e/evo2_1b_base.pt

Extra keys in state_dict: {'blocks.24.mixer.dense._extra_state', 'blocks.3.mixer.dense._extra_state', 'blocks.10.mixer.dense._extra_state', 'unembed.weight', 'blocks.17.mixer.dense._extra_state'}

[09/07/26 10:53:36] INFO     StripedHyena - INFO - Adjusting Wqkv for column split (permuting rows)   ]8;id=363606;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py\model.py]8;;\:]8;id=769408;file:///usr/local/lib/python3.12/dist-packages/vortex/model/model.py#1008\1008]8;;\

In [6]:
# Build mappings of unique reference sequences
ref_seqs = []
ref_seq_to_index = {}

# Parse sequences and store indexes
ref_seq_indexes = []
var_seqs = []

for _, row in brca1_df.iterrows():
    ref_seq, var_seq = parse_sequences(row['pos'], row['ref'], row['alt'])

    # Get or create index for reference sequence
    if ref_seq not in ref_seq_to_index:
        ref_seq_to_index[ref_seq] = len(ref_seqs)
        ref_seqs.append(ref_seq)
    
    ref_seq_indexes.append(ref_seq_to_index[ref_seq])
    var_seqs.append(var_seq)

ref_seq_indexes = np.array(ref_seq_indexes)

print(f'Scoring likelihoods of {len(ref_seqs)} reference sequences with Evo 2...')
ref_scores = model.score_sequences(ref_seqs)

print(f'Scoring likelihoods of {len(var_seqs)} variant sequences with Evo 2...')
var_scores = model.score_sequences(var_seqs)

Scoring likelihoods of 1326 reference sequences with Evo 2...

  0%|                                                        | 0/1326 [00:00<?, ?it/s]

[09/07/26 10:53:37] INFO     vortex.model.utils - INFO - Fixup applied: Allocating cublas workspace    ]8;id=973512;file:///usr/local/lib/python3.12/dist-packages/vortex/model/utils.py\utils.py]8;;\:]8;id=358062;file:///usr/local/lib/python3.12/dist-packages/vortex/model/utils.py#191\191]8;;\
                             for device=0

  0%|                                                | 1/1326 [00:01<28:18,  1.28s/it]

  0%|                                                | 2/1326 [00:01<15:24,  1.43it/s]

  0%|                                                | 3/1326 [00:01<11:17,  1.95it/s]

  0%|▏                                               | 4/1326 [00:02<09:20,  2.36it/s]

  0%|▏                                               | 5/1326 [00:02<08:16,  2.66it/s]

  0%|▏                                               | 6/1326 [00:02<07:37,  2.88it/s]

  1%|▎                                               | 7/1326 [00:03<07:12,  3.05it/s]

  1%|▎                                               | 8/1326 [00:03<06:56,  3.16it/s]

  1%|▎                                               | 9/1326 [00:03<06:45,  3.25it/s]

  1%|▎                                              | 10/1326 [00:03<06:38,  3.31it/s]

  1%|▍                                              | 11/1326 [00:04<06:32,  3.35it/s]

  1%|▍                                              | 12/1326 [00:04<06:29,  3.38it/s]

  1%|▍                                              | 13/1326 [00:04<06:26,  3.40it/s]

  1%|▍                                              | 14/1326 [00:05<06:24,  3.41it/s]

  1%|▌                                              | 15/1326 [00:05<06:23,  3.42it/s]

  1%|▌                                              | 16/1326 [00:05<06:22,  3.43it/s]

  1%|▌                                              | 17/1326 [00:05<06:21,  3.43it/s]

  1%|▋                                              | 18/1326 [00:06<06:20,  3.44it/s]

  1%|▋                                              | 19/1326 [00:06<06:20,  3.44it/s]

  2%|▋                                              | 20/1326 [00:06<06:19,  3.44it/s]

  2%|▋                                              | 21/1326 [00:07<06:19,  3.44it/s]

  2%|▊                                              | 22/1326 [00:07<06:18,  3.44it/s]

  2%|▊                                              | 23/1326 [00:07<06:18,  3.44it/s]

  2%|▊                                              | 24/1326 [00:07<06:18,  3.44it/s]

  2%|▉                                              | 25/1326 [00:08<06:17,  3.44it/s]

  2%|▉                                              | 26/1326 [00:08<06:17,  3.44it/s]

  2%|▉                                              | 27/1326 [00:08<06:17,  3.44it/s]

  2%|▉                                              | 28/1326 [00:09<06:17,  3.44it/s]

  2%|█                                              | 29/1326 [00:09<06:16,  3.44it/s]

  2%|█                                              | 30/1326 [00:09<06:16,  3.44it/s]

  2%|█                                              | 31/1326 [00:09<06:16,  3.44it/s]

  2%|█▏                                             | 32/1326 [00:10<06:15,  3.44it/s]

  2%|█▏                                             | 33/1326 [00:10<06:15,  3.44it/s]

  3%|█▏                                             | 34/1326 [00:10<06:15,  3.44it/s]

  3%|█▏                                             | 35/1326 [00:11<06:15,  3.44it/s]

  3%|█▎                                             | 36/1326 [00:11<06:15,  3.44it/s]

  3%|█▎                                             | 37/1326 [00:11<06:14,  3.44it/s]

  3%|█▎                                             | 38/1326 [00:12<06:14,  3.44it/s]

  3%|█▍                                             | 39/1326 [00:12<06:14,  3.44it/s]

  3%|█▍                                             | 40/1326 [00:12<06:13,  3.44it/s]

  3%|█▍                                             | 41/1326 [00:12<06:13,  3.44it/s]

  3%|█▍                                             | 42/1326 [00:13<06:13,  3.44it/s]

  3%|█▌                                             | 43/1326 [00:13<06:13,  3.44it/s]

  3%|█▌                                             | 44/1326 [00:13<06:12,  3.44it/s]

  3%|█▌                                             | 45/1326 [00:14<06:12,  3.44it/s]

  3%|█▋                                             | 46/1326 [00:14<06:12,  3.44it/s]

  4%|█▋                                             | 47/1326 [00:14<06:12,  3.44it/s]

  4%|█▋                                             | 48/1326 [00:14<06:11,  3.44it/s]

  4%|█▋                                             | 49/1326 [00:15<06:11,  3.44it/s]

  4%|█▊                                             | 50/1326 [00:15<06:11,  3.44it/s]

  4%|█▊                                             | 51/1326 [00:15<06:10,  3.44it/s]

  4%|█▊                                             | 52/1326 [00:16<06:10,  3.44it/s]

  4%|█▉                                             | 53/1326 [00:16<06:10,  3.44it/s]

  4%|█▉                                             | 54/1326 [00:16<06:10,  3.44it/s]

  4%|█▉                                             | 55/1326 [00:16<06:09,  3.44it/s]

  4%|█▉                                             | 56/1326 [00:17<06:09,  3.44it/s]

  4%|██                                             | 57/1326 [00:17<06:09,  3.44it/s]

  4%|██                                             | 58/1326 [00:17<06:08,  3.44it/s]

  4%|██                                             | 59/1326 [00:18<06:08,  3.44it/s]

  5%|██▏                                            | 60/1326 [00:18<06:08,  3.44it/s]

  5%|██▏                                            | 61/1326 [00:18<06:08,  3.44it/s]

  5%|██▏                                            | 62/1326 [00:19<06:07,  3.44it/s]

  5%|██▏                                            | 63/1326 [00:19<06:07,  3.44it/s]

  5%|██▎                                            | 64/1326 [00:19<06:07,  3.44it/s]

  5%|██▎                                            | 65/1326 [00:19<06:07,  3.43it/s]

  5%|██▎                                            | 66/1326 [00:20<06:06,  3.43it/s]

  5%|██▎                                            | 67/1326 [00:20<06:06,  3.43it/s]

  5%|██▍                                            | 68/1326 [00:20<06:06,  3.44it/s]

  5%|██▍                                            | 69/1326 [00:21<06:05,  3.44it/s]

  5%|██▍                                            | 70/1326 [00:21<06:05,  3.43it/s]

  5%|██▌                                            | 71/1326 [00:21<06:05,  3.43it/s]

  5%|██▌                                            | 72/1326 [00:21<06:05,  3.43it/s]

  6%|██▌                                            | 73/1326 [00:22<06:04,  3.43it/s]

  6%|██▌                                            | 74/1326 [00:22<06:04,  3.43it/s]

  6%|██▋                                            | 75/1326 [00:22<06:04,  3.43it/s]

  6%|██▋                                            | 76/1326 [00:23<06:04,  3.43it/s]

  6%|██▋                                            | 77/1326 [00:23<06:03,  3.43it/s]

  6%|██▊                                            | 78/1326 [00:23<06:03,  3.43it/s]

  6%|██▊                                            | 79/1326 [00:23<06:03,  3.43it/s]

  6%|██▊                                            | 80/1326 [00:24<06:03,  3.43it/s]

  6%|██▊                                            | 81/1326 [00:24<06:02,  3.43it/s]

  6%|██▉                                            | 82/1326 [00:24<06:02,  3.43it/s]

  6%|██▉                                            | 83/1326 [00:25<06:02,  3.43it/s]

  6%|██▉                                            | 84/1326 [00:25<06:02,  3.43it/s]

  6%|███                                            | 85/1326 [00:25<06:01,  3.43it/s]

  6%|███                                            | 86/1326 [00:26<06:01,  3.43it/s]

  7%|███                                            | 87/1326 [00:26<06:01,  3.43it/s]

  7%|███                                            | 88/1326 [00:26<06:01,  3.43it/s]

  7%|███▏                                           | 89/1326 [00:26<06:00,  3.43it/s]

  7%|███▏                                           | 90/1326 [00:27<06:00,  3.43it/s]

  7%|███▏                                           | 91/1326 [00:27<06:00,  3.43it/s]

  7%|███▎                                           | 92/1326 [00:27<05:59,  3.43it/s]

  7%|███▎                                           | 93/1326 [00:28<05:59,  3.43it/s]

  7%|███▎                                           | 94/1326 [00:28<05:59,  3.43it/s]

  7%|███▎                                           | 95/1326 [00:28<05:59,  3.43it/s]

  7%|███▍                                           | 96/1326 [00:28<05:58,  3.43it/s]

  7%|███▍                                           | 97/1326 [00:29<05:58,  3.43it/s]

  7%|███▍                                           | 98/1326 [00:29<05:58,  3.43it/s]

  7%|███▌                                           | 99/1326 [00:29<05:57,  3.43it/s]

  8%|███▍                                          | 100/1326 [00:30<05:57,  3.43it/s]

  8%|███▌                                          | 101/1326 [00:30<05:57,  3.43it/s]

  8%|███▌                                          | 102/1326 [00:30<05:57,  3.43it/s]

  8%|███▌                                          | 103/1326 [00:30<05:57,  3.42it/s]

  8%|███▌                                          | 104/1326 [00:31<05:56,  3.43it/s]

  8%|███▋                                          | 105/1326 [00:31<05:56,  3.43it/s]

  8%|███▋                                          | 106/1326 [00:31<05:56,  3.42it/s]

  8%|███▋                                          | 107/1326 [00:32<05:55,  3.43it/s]

  8%|███▋                                          | 108/1326 [00:32<05:55,  3.43it/s]

  8%|███▊                                          | 109/1326 [00:32<05:55,  3.43it/s]

  8%|███▊                                          | 110/1326 [00:33<05:54,  3.43it/s]

  8%|███▊                                          | 111/1326 [00:33<05:54,  3.43it/s]

  8%|███▉                                          | 112/1326 [00:33<05:54,  3.43it/s]

  9%|███▉                                          | 113/1326 [00:33<05:54,  3.43it/s]

  9%|███▉                                          | 114/1326 [00:34<05:53,  3.43it/s]

  9%|███▉                                          | 115/1326 [00:34<05:53,  3.43it/s]

  9%|████                                          | 116/1326 [00:34<05:53,  3.43it/s]

  9%|████                                          | 117/1326 [00:35<05:53,  3.42it/s]

  9%|████                                          | 118/1326 [00:35<05:52,  3.43it/s]

  9%|████▏                                         | 119/1326 [00:35<05:52,  3.43it/s]

  9%|████▏                                         | 120/1326 [00:35<05:52,  3.43it/s]

  9%|████▏                                         | 121/1326 [00:36<05:51,  3.42it/s]

  9%|████▏                                         | 122/1326 [00:36<05:51,  3.42it/s]

  9%|████▎                                         | 123/1326 [00:36<05:51,  3.42it/s]

  9%|████▎                                         | 124/1326 [00:37<05:51,  3.42it/s]

  9%|████▎                                         | 125/1326 [00:37<05:50,  3.42it/s]

 10%|████▎                                         | 126/1326 [00:37<05:50,  3.42it/s]

 10%|████▍                                         | 127/1326 [00:37<05:50,  3.42it/s]

 10%|████▍                                         | 128/1326 [00:38<05:49,  3.42it/s]

 10%|████▍                                         | 129/1326 [00:38<05:49,  3.42it/s]

 10%|████▌                                         | 130/1326 [00:38<05:49,  3.42it/s]

 10%|████▌                                         | 131/1326 [00:39<05:49,  3.42it/s]

 10%|████▌                                         | 132/1326 [00:39<05:48,  3.42it/s]

 10%|████▌                                         | 133/1326 [00:39<05:48,  3.42it/s]

 10%|████▋                                         | 134/1326 [00:40<05:48,  3.42it/s]

 10%|████▋                                         | 135/1326 [00:40<05:48,  3.42it/s]

 10%|████▋                                         | 136/1326 [00:40<05:47,  3.42it/s]

 10%|████▊                                         | 137/1326 [00:40<05:47,  3.42it/s]

 10%|████▊                                         | 138/1326 [00:41<05:47,  3.42it/s]

 10%|████▊                                         | 139/1326 [00:41<05:47,  3.42it/s]

 11%|████▊                                         | 140/1326 [00:41<05:46,  3.42it/s]

 11%|████▉                                         | 141/1326 [00:42<05:46,  3.42it/s]

 11%|████▉                                         | 142/1326 [00:42<05:46,  3.42it/s]

 11%|████▉                                         | 143/1326 [00:42<05:46,  3.42it/s]

 11%|████▉                                         | 144/1326 [00:42<05:45,  3.42it/s]

 11%|█████                                         | 145/1326 [00:43<05:45,  3.42it/s]

 11%|█████                                         | 146/1326 [00:43<05:45,  3.42it/s]

 11%|█████                                         | 147/1326 [00:43<05:45,  3.42it/s]

 11%|█████▏                                        | 148/1326 [00:44<05:44,  3.42it/s]

 11%|█████▏                                        | 149/1326 [00:44<05:44,  3.42it/s]

 11%|█████▏                                        | 150/1326 [00:44<05:44,  3.42it/s]

 11%|█████▏                                        | 151/1326 [00:44<05:43,  3.42it/s]

 11%|█████▎                                        | 152/1326 [00:45<05:43,  3.42it/s]

 12%|█████▎                                        | 153/1326 [00:45<05:43,  3.41it/s]

 12%|█████▎                                        | 154/1326 [00:45<05:43,  3.42it/s]

 12%|█████▍                                        | 155/1326 [00:46<05:43,  3.41it/s]

 12%|█████▍                                        | 156/1326 [00:46<05:42,  3.41it/s]

 12%|█████▍                                        | 157/1326 [00:46<05:42,  3.41it/s]

 12%|█████▍                                        | 158/1326 [00:47<05:42,  3.41it/s]

 12%|█████▌                                        | 159/1326 [00:47<05:41,  3.41it/s]

 12%|█████▌                                        | 160/1326 [00:47<05:41,  3.41it/s]

 12%|█████▌                                        | 161/1326 [00:47<05:41,  3.41it/s]

 12%|█████▌                                        | 162/1326 [00:48<05:41,  3.41it/s]

 12%|█████▋                                        | 163/1326 [00:48<05:40,  3.41it/s]

 12%|█████▋                                        | 164/1326 [00:48<05:40,  3.41it/s]

 12%|█████▋                                        | 165/1326 [00:49<05:40,  3.41it/s]

 13%|█████▊                                        | 166/1326 [00:49<05:39,  3.41it/s]

 13%|█████▊                                        | 167/1326 [00:49<05:39,  3.41it/s]

 13%|█████▊                                        | 168/1326 [00:49<05:39,  3.41it/s]

 13%|█████▊                                        | 169/1326 [00:50<05:38,  3.41it/s]

 13%|█████▉                                        | 170/1326 [00:50<05:38,  3.41it/s]

 13%|█████▉                                        | 171/1326 [00:50<05:38,  3.41it/s]

 13%|█████▉                                        | 172/1326 [00:51<05:37,  3.41it/s]

 13%|██████                                        | 173/1326 [00:51<05:37,  3.41it/s]

 13%|██████                                        | 174/1326 [00:51<05:37,  3.41it/s]

 13%|██████                                        | 175/1326 [00:52<05:37,  3.41it/s]

 13%|██████                                        | 176/1326 [00:52<05:36,  3.41it/s]

 13%|██████▏                                       | 177/1326 [00:52<05:36,  3.41it/s]

 13%|██████▏                                       | 178/1326 [00:52<05:36,  3.41it/s]

 13%|██████▏                                       | 179/1326 [00:53<05:36,  3.41it/s]

 14%|██████▏                                       | 180/1326 [00:53<05:35,  3.41it/s]

 14%|██████▎                                       | 181/1326 [00:53<05:35,  3.41it/s]

 14%|██████▎                                       | 182/1326 [00:54<05:35,  3.41it/s]

 14%|██████▎                                       | 183/1326 [00:54<05:34,  3.41it/s]

 14%|██████▍                                       | 184/1326 [00:54<05:34,  3.41it/s]

 14%|██████▍                                       | 185/1326 [00:54<05:34,  3.41it/s]

 14%|██████▍                                       | 186/1326 [00:55<05:34,  3.41it/s]

 14%|██████▍                                       | 187/1326 [00:55<05:33,  3.41it/s]

 14%|██████▌                                       | 188/1326 [00:55<05:33,  3.41it/s]

 14%|██████▌                                       | 189/1326 [00:56<05:33,  3.41it/s]

 14%|██████▌                                       | 190/1326 [00:56<05:33,  3.41it/s]

 14%|██████▋                                       | 191/1326 [00:56<05:32,  3.41it/s]

 14%|██████▋                                       | 192/1326 [00:57<05:32,  3.41it/s]

 15%|██████▋                                       | 193/1326 [00:57<05:32,  3.41it/s]

 15%|██████▋                                       | 194/1326 [00:57<05:31,  3.41it/s]

 15%|██████▊                                       | 195/1326 [00:57<05:31,  3.41it/s]

 15%|██████▊                                       | 196/1326 [00:58<05:31,  3.41it/s]

 15%|██████▊                                       | 197/1326 [00:58<05:31,  3.41it/s]

 15%|██████▊                                       | 198/1326 [00:58<05:30,  3.41it/s]

 15%|██████▉                                       | 199/1326 [00:59<05:30,  3.41it/s]

 15%|██████▉                                       | 200/1326 [00:59<05:30,  3.41it/s]

 15%|██████▉                                       | 201/1326 [00:59<05:29,  3.41it/s]

 15%|███████                                       | 202/1326 [00:59<05:29,  3.41it/s]

 15%|███████                                       | 203/1326 [01:00<05:29,  3.41it/s]

 15%|███████                                       | 204/1326 [01:00<05:28,  3.41it/s]

 15%|███████                                       | 205/1326 [01:00<05:28,  3.41it/s]

 16%|███████▏                                      | 206/1326 [01:01<05:28,  3.41it/s]

 16%|███████▏                                      | 207/1326 [01:01<05:28,  3.41it/s]

 16%|███████▏                                      | 208/1326 [01:01<05:27,  3.41it/s]

 16%|███████▎                                      | 209/1326 [01:01<05:27,  3.41it/s]

 16%|███████▎                                      | 210/1326 [01:02<05:26,  3.41it/s]

 16%|███████▎                                      | 211/1326 [01:02<05:26,  3.41it/s]

 16%|███████▎                                      | 212/1326 [01:02<05:26,  3.41it/s]

 16%|███████▍                                      | 213/1326 [01:03<05:25,  3.41it/s]

 16%|███████▍                                      | 214/1326 [01:03<05:25,  3.41it/s]

 16%|███████▍                                      | 215/1326 [01:03<05:25,  3.41it/s]

 16%|███████▍                                      | 216/1326 [01:04<05:25,  3.41it/s]

 16%|███████▌                                      | 217/1326 [01:04<05:24,  3.41it/s]

 16%|███████▌                                      | 218/1326 [01:04<05:24,  3.41it/s]

 17%|███████▌                                      | 219/1326 [01:04<05:24,  3.41it/s]

 17%|███████▋                                      | 220/1326 [01:05<05:24,  3.41it/s]

 17%|███████▋                                      | 221/1326 [01:05<05:23,  3.41it/s]

 17%|███████▋                                      | 222/1326 [01:05<05:23,  3.41it/s]

 17%|███████▋                                      | 223/1326 [01:06<05:23,  3.41it/s]

 17%|███████▊                                      | 224/1326 [01:06<05:22,  3.41it/s]

 17%|███████▊                                      | 225/1326 [01:06<05:22,  3.41it/s]

 17%|███████▊                                      | 226/1326 [01:06<05:22,  3.41it/s]

 17%|███████▊                                      | 227/1326 [01:07<05:21,  3.41it/s]

 17%|███████▉                                      | 228/1326 [01:07<05:21,  3.41it/s]

 17%|███████▉                                      | 229/1326 [01:07<05:21,  3.41it/s]

 17%|███████▉                                      | 230/1326 [01:08<05:21,  3.41it/s]

 17%|████████                                      | 231/1326 [01:08<05:20,  3.41it/s]

 17%|████████                                      | 232/1326 [01:08<05:20,  3.41it/s]

 18%|████████                                      | 233/1326 [01:09<05:20,  3.41it/s]

 18%|████████                                      | 234/1326 [01:09<05:19,  3.41it/s]

 18%|████████▏                                     | 235/1326 [01:09<05:19,  3.41it/s]

 18%|████████▏                                     | 236/1326 [01:09<05:19,  3.41it/s]

 18%|████████▏                                     | 237/1326 [01:10<05:19,  3.41it/s]

 18%|████████▎                                     | 238/1326 [01:10<05:18,  3.41it/s]

 18%|████████▎                                     | 239/1326 [01:10<05:18,  3.41it/s]

 18%|████████▎                                     | 240/1326 [01:11<05:18,  3.41it/s]

 18%|████████▎                                     | 241/1326 [01:11<05:17,  3.41it/s]

 18%|████████▍                                     | 242/1326 [01:11<05:17,  3.41it/s]

 18%|████████▍                                     | 243/1326 [01:11<05:17,  3.41it/s]

 18%|████████▍                                     | 244/1326 [01:12<05:17,  3.41it/s]

 18%|████████▍                                     | 245/1326 [01:12<05:17,  3.41it/s]

 19%|████████▌                                     | 246/1326 [01:12<05:16,  3.41it/s]

 19%|████████▌                                     | 247/1326 [01:13<05:16,  3.41it/s]

 19%|████████▌                                     | 248/1326 [01:13<05:16,  3.41it/s]

 19%|████████▋                                     | 249/1326 [01:13<05:15,  3.41it/s]

 19%|████████▋                                     | 250/1326 [01:14<05:15,  3.41it/s]

 19%|████████▋                                     | 251/1326 [01:14<05:15,  3.41it/s]

 19%|████████▋                                     | 252/1326 [01:14<05:14,  3.41it/s]

 19%|████████▊                                     | 253/1326 [01:14<05:14,  3.41it/s]

 19%|████████▊                                     | 254/1326 [01:15<05:14,  3.41it/s]

 19%|████████▊                                     | 255/1326 [01:15<05:14,  3.41it/s]

 19%|████████▉                                     | 256/1326 [01:15<05:13,  3.41it/s]

 19%|████████▉                                     | 257/1326 [01:16<05:13,  3.41it/s]

 19%|████████▉                                     | 258/1326 [01:16<05:13,  3.41it/s]

 20%|████████▉                                     | 259/1326 [01:16<05:12,  3.41it/s]

 20%|█████████                                     | 260/1326 [01:16<05:12,  3.41it/s]

 20%|█████████                                     | 261/1326 [01:17<05:12,  3.41it/s]

 20%|█████████                                     | 262/1326 [01:17<05:12,  3.41it/s]

 20%|█████████                                     | 263/1326 [01:17<05:11,  3.41it/s]

 20%|█████████▏                                    | 264/1326 [01:18<05:11,  3.41it/s]

 20%|█████████▏                                    | 265/1326 [01:18<05:11,  3.41it/s]

 20%|█████████▏                                    | 266/1326 [01:18<05:11,  3.41it/s]

 20%|█████████▎                                    | 267/1326 [01:18<05:10,  3.41it/s]

 20%|█████████▎                                    | 268/1326 [01:19<05:10,  3.41it/s]

 20%|█████████▎                                    | 269/1326 [01:19<05:10,  3.41it/s]

 20%|█████████▎                                    | 270/1326 [01:19<05:10,  3.41it/s]

 20%|█████████▍                                    | 271/1326 [01:20<05:09,  3.41it/s]

 21%|█████████▍                                    | 272/1326 [01:20<05:09,  3.41it/s]

 21%|█████████▍                                    | 273/1326 [01:20<05:09,  3.41it/s]

 21%|█████████▌                                    | 274/1326 [01:21<05:08,  3.41it/s]

 21%|█████████▌                                    | 275/1326 [01:21<05:08,  3.41it/s]

 21%|█████████▌                                    | 276/1326 [01:21<05:08,  3.41it/s]

 21%|█████████▌                                    | 277/1326 [01:21<05:07,  3.41it/s]

 21%|█████████▋                                    | 278/1326 [01:22<05:07,  3.41it/s]

 21%|█████████▋                                    | 279/1326 [01:22<05:07,  3.41it/s]

 21%|█████████▋                                    | 280/1326 [01:22<05:07,  3.41it/s]

 21%|█████████▋                                    | 281/1326 [01:23<05:06,  3.41it/s]

 21%|█████████▊                                    | 282/1326 [01:23<05:06,  3.41it/s]

 21%|█████████▊                                    | 283/1326 [01:23<05:06,  3.41it/s]

 21%|█████████▊                                    | 284/1326 [01:23<05:05,  3.41it/s]

 21%|█████████▉                                    | 285/1326 [01:24<05:05,  3.41it/s]

 22%|█████████▉                                    | 286/1326 [01:24<05:05,  3.41it/s]

 22%|█████████▉                                    | 287/1326 [01:24<05:04,  3.41it/s]

 22%|█████████▉                                    | 288/1326 [01:25<05:04,  3.41it/s]

 22%|██████████                                    | 289/1326 [01:25<05:04,  3.41it/s]

 22%|██████████                                    | 290/1326 [01:25<05:04,  3.41it/s]

 22%|██████████                                    | 291/1326 [01:26<05:03,  3.41it/s]

 22%|██████████▏                                   | 292/1326 [01:26<05:03,  3.40it/s]

 22%|██████████▏                                   | 293/1326 [01:26<05:03,  3.40it/s]

 22%|██████████▏                                   | 294/1326 [01:26<05:03,  3.41it/s]

 22%|██████████▏                                   | 295/1326 [01:27<05:02,  3.41it/s]

 22%|██████████▎                                   | 296/1326 [01:27<05:02,  3.40it/s]

 22%|██████████▎                                   | 297/1326 [01:27<05:02,  3.41it/s]

 22%|██████████▎                                   | 298/1326 [01:28<05:01,  3.40it/s]

 23%|██████████▎                                   | 299/1326 [01:28<05:01,  3.40it/s]

 23%|██████████▍                                   | 300/1326 [01:28<05:01,  3.41it/s]

 23%|██████████▍                                   | 301/1326 [01:28<05:01,  3.40it/s]

 23%|██████████▍                                   | 302/1326 [01:29<05:00,  3.40it/s]

 23%|██████████▌                                   | 303/1326 [01:29<05:00,  3.40it/s]

 23%|██████████▌                                   | 304/1326 [01:29<05:00,  3.40it/s]

 23%|██████████▌                                   | 305/1326 [01:30<04:59,  3.40it/s]

 23%|██████████▌                                   | 306/1326 [01:30<04:59,  3.40it/s]

 23%|██████████▋                                   | 307/1326 [01:30<04:59,  3.40it/s]

 23%|██████████▋                                   | 308/1326 [01:31<04:59,  3.40it/s]

 23%|██████████▋                                   | 309/1326 [01:31<04:58,  3.40it/s]

 23%|██████████▊                                   | 310/1326 [01:31<04:58,  3.40it/s]

 23%|██████████▊                                   | 311/1326 [01:31<04:58,  3.40it/s]

 24%|██████████▊                                   | 312/1326 [01:32<04:58,  3.40it/s]

 24%|██████████▊                                   | 313/1326 [01:32<04:57,  3.40it/s]

 24%|██████████▉                                   | 314/1326 [01:32<04:57,  3.40it/s]

 24%|██████████▉                                   | 315/1326 [01:33<04:57,  3.40it/s]

 24%|██████████▉                                   | 316/1326 [01:33<04:56,  3.40it/s]

 24%|██████████▉                                   | 317/1326 [01:33<04:56,  3.40it/s]

 24%|███████████                                   | 318/1326 [01:33<04:56,  3.40it/s]

 24%|███████████                                   | 319/1326 [01:34<04:56,  3.40it/s]

 24%|███████████                                   | 320/1326 [01:34<04:55,  3.40it/s]

 24%|███████████▏                                  | 321/1326 [01:34<04:55,  3.40it/s]

 24%|███████████▏                                  | 322/1326 [01:35<04:55,  3.40it/s]

 24%|███████████▏                                  | 323/1326 [01:35<04:55,  3.40it/s]

 24%|███████████▏                                  | 324/1326 [01:35<04:54,  3.40it/s]

 25%|███████████▎                                  | 325/1326 [01:36<04:54,  3.40it/s]

 25%|███████████▎                                  | 326/1326 [01:36<04:54,  3.40it/s]

 25%|███████████▎                                  | 327/1326 [01:36<04:53,  3.40it/s]

 25%|███████████▍                                  | 328/1326 [01:36<04:53,  3.40it/s]

 25%|███████████▍                                  | 329/1326 [01:37<04:53,  3.40it/s]

 25%|███████████▍                                  | 330/1326 [01:37<04:52,  3.40it/s]

 25%|███████████▍                                  | 331/1326 [01:37<04:52,  3.40it/s]

 25%|███████████▌                                  | 332/1326 [01:38<04:52,  3.40it/s]

 25%|███████████▌                                  | 333/1326 [01:38<04:52,  3.40it/s]

 25%|███████████▌                                  | 334/1326 [01:38<04:51,  3.40it/s]

 25%|███████████▌                                  | 335/1326 [01:38<04:51,  3.40it/s]

 25%|███████████▋                                  | 336/1326 [01:39<04:51,  3.40it/s]

 25%|███████████▋                                  | 337/1326 [01:39<04:50,  3.40it/s]

 25%|███████████▋                                  | 338/1326 [01:39<04:50,  3.40it/s]

 26%|███████████▊                                  | 339/1326 [01:40<04:50,  3.40it/s]

 26%|███████████▊                                  | 340/1326 [01:40<04:49,  3.40it/s]

 26%|███████████▊                                  | 341/1326 [01:40<04:49,  3.41it/s]

 26%|███████████▊                                  | 342/1326 [01:41<04:48,  3.41it/s]

 26%|███████████▉                                  | 343/1326 [01:41<04:48,  3.41it/s]

 26%|███████████▉                                  | 344/1326 [01:41<04:48,  3.41it/s]

 26%|███████████▉                                  | 345/1326 [01:41<04:47,  3.41it/s]

 26%|████████████                                  | 346/1326 [01:42<04:47,  3.41it/s]

 26%|████████████                                  | 347/1326 [01:42<04:47,  3.41it/s]

 26%|████████████                                  | 348/1326 [01:42<04:46,  3.41it/s]

 26%|████████████                                  | 349/1326 [01:43<04:46,  3.41it/s]

 26%|████████████▏                                 | 350/1326 [01:43<04:46,  3.41it/s]

 26%|████████████▏                                 | 351/1326 [01:43<04:45,  3.41it/s]

 27%|████████████▏                                 | 352/1326 [01:43<04:45,  3.41it/s]

 27%|████████████▏                                 | 353/1326 [01:44<04:45,  3.41it/s]

 27%|████████████▎                                 | 354/1326 [01:44<04:45,  3.41it/s]

 27%|████████████▎                                 | 355/1326 [01:44<04:45,  3.41it/s]

 27%|████████████▎                                 | 356/1326 [01:45<04:44,  3.41it/s]

 27%|████████████▍                                 | 357/1326 [01:45<04:44,  3.41it/s]

 27%|████████████▍                                 | 358/1326 [01:45<04:44,  3.41it/s]

 27%|████████████▍                                 | 359/1326 [01:46<04:43,  3.41it/s]

 27%|████████████▍                                 | 360/1326 [01:46<04:43,  3.41it/s]

 27%|████████████▌                                 | 361/1326 [01:46<04:43,  3.41it/s]

 27%|████████████▌                                 | 362/1326 [01:46<04:42,  3.41it/s]

 27%|████████████▌                                 | 363/1326 [01:47<04:42,  3.41it/s]

 27%|████████████▋                                 | 364/1326 [01:47<04:42,  3.41it/s]

 28%|████████████▋                                 | 365/1326 [01:47<04:42,  3.41it/s]

 28%|████████████▋                                 | 366/1326 [01:48<04:41,  3.41it/s]

 28%|████████████▋                                 | 367/1326 [01:48<04:41,  3.41it/s]

 28%|████████████▊                                 | 368/1326 [01:48<04:41,  3.41it/s]

 28%|████████████▊                                 | 369/1326 [01:48<04:40,  3.41it/s]

 28%|████████████▊                                 | 370/1326 [01:49<04:40,  3.40it/s]

 28%|████████████▊                                 | 371/1326 [01:49<04:40,  3.40it/s]

 28%|████████████▉                                 | 372/1326 [01:49<04:40,  3.40it/s]

 28%|████████████▉                                 | 373/1326 [01:50<04:39,  3.40it/s]

 28%|████████████▉                                 | 374/1326 [01:50<04:39,  3.40it/s]

 28%|█████████████                                 | 375/1326 [01:50<04:39,  3.41it/s]

 28%|█████████████                                 | 376/1326 [01:51<04:38,  3.41it/s]

 28%|█████████████                                 | 377/1326 [01:51<04:38,  3.41it/s]

 29%|█████████████                                 | 378/1326 [01:51<04:38,  3.41it/s]

 29%|█████████████▏                                | 379/1326 [01:51<04:37,  3.41it/s]

 29%|█████████████▏                                | 380/1326 [01:52<04:37,  3.41it/s]

 29%|█████████████▏                                | 381/1326 [01:52<04:37,  3.41it/s]

 29%|█████████████▎                                | 382/1326 [01:52<04:37,  3.41it/s]

 29%|█████████████▎                                | 383/1326 [01:53<04:36,  3.41it/s]

 29%|█████████████▎                                | 384/1326 [01:53<04:36,  3.41it/s]

 29%|█████████████▎                                | 385/1326 [01:53<04:36,  3.41it/s]

 29%|█████████████▍                                | 386/1326 [01:53<04:35,  3.41it/s]

 29%|█████████████▍                                | 387/1326 [01:54<04:35,  3.40it/s]

 29%|█████████████▍                                | 388/1326 [01:54<04:35,  3.40it/s]

 29%|█████████████▍                                | 389/1326 [01:54<04:35,  3.40it/s]

 29%|█████████████▌                                | 390/1326 [01:55<04:35,  3.40it/s]

 29%|█████████████▌                                | 391/1326 [01:55<04:34,  3.40it/s]

 30%|█████████████▌                                | 392/1326 [01:55<04:34,  3.40it/s]

 30%|█████████████▋                                | 393/1326 [01:55<04:34,  3.40it/s]

 30%|█████████████▋                                | 394/1326 [01:56<04:33,  3.41it/s]

 30%|█████████████▋                                | 395/1326 [01:56<04:33,  3.40it/s]

 30%|█████████████▋                                | 396/1326 [01:56<04:33,  3.41it/s]

 30%|█████████████▊                                | 397/1326 [01:57<04:32,  3.41it/s]

 30%|█████████████▊                                | 398/1326 [01:57<04:32,  3.41it/s]

 30%|█████████████▊                                | 399/1326 [01:57<04:32,  3.41it/s]

 30%|█████████████▉                                | 400/1326 [01:58<04:31,  3.41it/s]

 30%|█████████████▉                                | 401/1326 [01:58<04:31,  3.41it/s]

 30%|█████████████▉                                | 402/1326 [01:58<04:31,  3.41it/s]

 30%|█████████████▉                                | 403/1326 [01:58<04:31,  3.41it/s]

 30%|██████████████                                | 404/1326 [01:59<04:30,  3.40it/s]

 31%|██████████████                                | 405/1326 [01:59<04:30,  3.40it/s]

 31%|██████████████                                | 406/1326 [01:59<04:30,  3.40it/s]

 31%|██████████████                                | 407/1326 [02:00<04:30,  3.40it/s]

 31%|██████████████▏                               | 408/1326 [02:00<04:29,  3.40it/s]

 31%|██████████████▏                               | 409/1326 [02:00<04:29,  3.40it/s]

 31%|██████████████▏                               | 410/1326 [02:00<04:29,  3.40it/s]

 31%|██████████████▎                               | 411/1326 [02:01<04:28,  3.40it/s]

 31%|██████████████▎                               | 412/1326 [02:01<04:28,  3.40it/s]

 31%|██████████████▎                               | 413/1326 [02:01<04:28,  3.40it/s]

 31%|██████████████▎                               | 414/1326 [02:02<04:27,  3.40it/s]

 31%|██████████████▍                               | 415/1326 [02:02<04:27,  3.40it/s]

 31%|██████████████▍                               | 416/1326 [02:02<04:27,  3.40it/s]

 31%|██████████████▍                               | 417/1326 [02:03<04:26,  3.40it/s]

 32%|██████████████▌                               | 418/1326 [02:03<04:26,  3.40it/s]

 32%|██████████████▌                               | 419/1326 [02:03<04:26,  3.40it/s]

 32%|██████████████▌                               | 420/1326 [02:03<04:26,  3.41it/s]

 32%|██████████████▌                               | 421/1326 [02:04<04:25,  3.41it/s]

 32%|██████████████▋                               | 422/1326 [02:04<04:25,  3.40it/s]

 32%|██████████████▋                               | 423/1326 [02:04<04:25,  3.41it/s]

 32%|██████████████▋                               | 424/1326 [02:05<04:24,  3.41it/s]

 32%|██████████████▋                               | 425/1326 [02:05<04:24,  3.41it/s]

 32%|██████████████▊                               | 426/1326 [02:05<04:24,  3.41it/s]

 32%|██████████████▊                               | 427/1326 [02:05<04:23,  3.41it/s]

 32%|██████████████▊                               | 428/1326 [02:06<04:23,  3.41it/s]

 32%|██████████████▉                               | 429/1326 [02:06<04:23,  3.41it/s]

 32%|██████████████▉                               | 430/1326 [02:06<04:23,  3.41it/s]

 33%|██████████████▉                               | 431/1326 [02:07<04:22,  3.41it/s]

 33%|██████████████▉                               | 432/1326 [02:07<04:22,  3.41it/s]

 33%|███████████████                               | 433/1326 [02:07<04:22,  3.41it/s]

 33%|███████████████                               | 434/1326 [02:08<04:21,  3.41it/s]

 33%|███████████████                               | 435/1326 [02:08<04:21,  3.41it/s]

 33%|███████████████▏                              | 436/1326 [02:08<04:21,  3.41it/s]

 33%|███████████████▏                              | 437/1326 [02:08<04:21,  3.41it/s]

 33%|███████████████▏                              | 438/1326 [02:09<04:20,  3.40it/s]

 33%|███████████████▏                              | 439/1326 [02:09<04:20,  3.41it/s]

 33%|███████████████▎                              | 440/1326 [02:09<04:20,  3.41it/s]

 33%|███████████████▎                              | 441/1326 [02:10<04:19,  3.40it/s]

 33%|███████████████▎                              | 442/1326 [02:10<04:19,  3.40it/s]

 33%|███████████████▎                              | 443/1326 [02:10<04:19,  3.40it/s]

 33%|███████████████▍                              | 444/1326 [02:10<04:19,  3.40it/s]

 34%|███████████████▍                              | 445/1326 [02:11<04:18,  3.40it/s]

 34%|███████████████▍                              | 446/1326 [02:11<04:18,  3.40it/s]

 34%|███████████████▌                              | 447/1326 [02:11<04:18,  3.40it/s]

 34%|███████████████▌                              | 448/1326 [02:12<04:17,  3.40it/s]

 34%|███████████████▌                              | 449/1326 [02:12<04:17,  3.40it/s]

 34%|███████████████▌                              | 450/1326 [02:12<04:17,  3.40it/s]

 34%|███████████████▋                              | 451/1326 [02:13<04:17,  3.40it/s]

 34%|███████████████▋                              | 452/1326 [02:13<04:16,  3.41it/s]

 34%|███████████████▋                              | 453/1326 [02:13<04:16,  3.41it/s]

 34%|███████████████▋                              | 454/1326 [02:13<04:15,  3.41it/s]

 34%|███████████████▊                              | 455/1326 [02:14<04:15,  3.41it/s]

 34%|███████████████▊                              | 456/1326 [02:14<04:15,  3.41it/s]

 34%|███████████████▊                              | 457/1326 [02:14<04:15,  3.41it/s]

 35%|███████████████▉                              | 458/1326 [02:15<04:14,  3.41it/s]

 35%|███████████████▉                              | 459/1326 [02:15<04:14,  3.41it/s]

 35%|███████████████▉                              | 460/1326 [02:15<04:14,  3.41it/s]

 35%|███████████████▉                              | 461/1326 [02:15<04:13,  3.41it/s]

 35%|████████████████                              | 462/1326 [02:16<04:13,  3.41it/s]

 35%|████████████████                              | 463/1326 [02:16<04:13,  3.41it/s]

 35%|████████████████                              | 464/1326 [02:16<04:13,  3.41it/s]

 35%|████████████████▏                             | 465/1326 [02:17<04:12,  3.41it/s]

 35%|████████████████▏                             | 466/1326 [02:17<04:12,  3.41it/s]

 35%|████████████████▏                             | 467/1326 [02:17<04:12,  3.41it/s]

 35%|████████████████▏                             | 468/1326 [02:18<04:11,  3.41it/s]

 35%|████████████████▎                             | 469/1326 [02:18<04:11,  3.41it/s]

 35%|████████████████▎                             | 470/1326 [02:18<04:11,  3.41it/s]

 36%|████████████████▎                             | 471/1326 [02:18<04:11,  3.41it/s]

 36%|████████████████▎                             | 472/1326 [02:19<04:10,  3.41it/s]

 36%|████████████████▍                             | 473/1326 [02:19<04:10,  3.41it/s]

 36%|████████████████▍                             | 474/1326 [02:19<04:10,  3.41it/s]

 36%|████████████████▍                             | 475/1326 [02:20<04:09,  3.41it/s]

 36%|████████████████▌                             | 476/1326 [02:20<04:09,  3.41it/s]

 36%|████████████████▌                             | 477/1326 [02:20<04:09,  3.41it/s]

 36%|████████████████▌                             | 478/1326 [02:20<04:08,  3.41it/s]

 36%|████████████████▌                             | 479/1326 [02:21<04:08,  3.41it/s]

 36%|████████████████▋                             | 480/1326 [02:21<04:08,  3.41it/s]

 36%|████████████████▋                             | 481/1326 [02:21<04:08,  3.41it/s]

 36%|████████████████▋                             | 482/1326 [02:22<04:07,  3.41it/s]

 36%|████████████████▊                             | 483/1326 [02:22<04:07,  3.41it/s]

 37%|████████████████▊                             | 484/1326 [02:22<04:07,  3.41it/s]

 37%|████████████████▊                             | 485/1326 [02:23<04:06,  3.41it/s]

 37%|████████████████▊                             | 486/1326 [02:23<04:06,  3.40it/s]

 37%|████████████████▉                             | 487/1326 [02:23<04:06,  3.41it/s]

 37%|████████████████▉                             | 488/1326 [02:23<04:06,  3.40it/s]

 37%|████████████████▉                             | 489/1326 [02:24<04:05,  3.40it/s]

 37%|████████████████▉                             | 490/1326 [02:24<04:05,  3.41it/s]

 37%|█████████████████                             | 491/1326 [02:24<04:05,  3.41it/s]

 37%|█████████████████                             | 492/1326 [02:25<04:04,  3.40it/s]

 37%|█████████████████                             | 493/1326 [02:25<04:04,  3.41it/s]

 37%|█████████████████▏                            | 494/1326 [02:25<04:04,  3.40it/s]

 37%|█████████████████▏                            | 495/1326 [02:25<04:04,  3.40it/s]

 37%|█████████████████▏                            | 496/1326 [02:26<04:03,  3.40it/s]

 37%|█████████████████▏                            | 497/1326 [02:26<04:03,  3.40it/s]

 38%|█████████████████▎                            | 498/1326 [02:26<04:03,  3.40it/s]

 38%|█████████████████▎                            | 499/1326 [02:27<04:02,  3.40it/s]

 38%|█████████████████▎                            | 500/1326 [02:27<04:02,  3.41it/s]

 38%|█████████████████▍                            | 501/1326 [02:27<04:02,  3.40it/s]

 38%|█████████████████▍                            | 502/1326 [02:28<04:01,  3.41it/s]

 38%|█████████████████▍                            | 503/1326 [02:28<04:01,  3.40it/s]

 38%|█████████████████▍                            | 504/1326 [02:28<04:01,  3.40it/s]

 38%|█████████████████▌                            | 505/1326 [02:28<04:01,  3.40it/s]

 38%|█████████████████▌                            | 506/1326 [02:29<04:00,  3.40it/s]

 38%|█████████████████▌                            | 507/1326 [02:29<04:00,  3.40it/s]

 38%|█████████████████▌                            | 508/1326 [02:29<04:00,  3.40it/s]

 38%|█████████████████▋                            | 509/1326 [02:30<04:00,  3.40it/s]

 38%|█████████████████▋                            | 510/1326 [02:30<03:59,  3.40it/s]

 39%|█████████████████▋                            | 511/1326 [02:30<03:59,  3.40it/s]

 39%|█████████████████▊                            | 512/1326 [02:30<03:59,  3.40it/s]

 39%|█████████████████▊                            | 513/1326 [02:31<03:58,  3.40it/s]

 39%|█████████████████▊                            | 514/1326 [02:31<03:58,  3.40it/s]

 39%|█████████████████▊                            | 515/1326 [02:31<03:58,  3.40it/s]

 39%|█████████████████▉                            | 516/1326 [02:32<03:57,  3.40it/s]

 39%|█████████████████▉                            | 517/1326 [02:32<03:57,  3.41it/s]

 39%|█████████████████▉                            | 518/1326 [02:32<03:57,  3.41it/s]

 39%|██████████████████                            | 519/1326 [02:32<03:56,  3.41it/s]

 39%|██████████████████                            | 520/1326 [02:33<03:56,  3.41it/s]

 39%|██████████████████                            | 521/1326 [02:33<03:56,  3.40it/s]

 39%|██████████████████                            | 522/1326 [02:33<03:56,  3.40it/s]

 39%|██████████████████▏                           | 523/1326 [02:34<03:55,  3.40it/s]

 40%|██████████████████▏                           | 524/1326 [02:34<03:55,  3.40it/s]

 40%|██████████████████▏                           | 525/1326 [02:34<03:55,  3.40it/s]

 40%|██████████████████▏                           | 526/1326 [02:35<03:55,  3.40it/s]

 40%|██████████████████▎                           | 527/1326 [02:35<03:54,  3.41it/s]

 40%|██████████████████▎                           | 528/1326 [02:35<03:54,  3.40it/s]

 40%|██████████████████▎                           | 529/1326 [02:35<03:54,  3.41it/s]

 40%|██████████████████▍                           | 530/1326 [02:36<03:53,  3.41it/s]

 40%|██████████████████▍                           | 531/1326 [02:36<03:53,  3.41it/s]

 40%|██████████████████▍                           | 532/1326 [02:36<03:53,  3.41it/s]

 40%|██████████████████▍                           | 533/1326 [02:37<03:52,  3.41it/s]

 40%|██████████████████▌                           | 534/1326 [02:37<03:52,  3.41it/s]

 40%|██████████████████▌                           | 535/1326 [02:37<03:52,  3.41it/s]

 40%|██████████████████▌                           | 536/1326 [02:37<03:51,  3.41it/s]

 40%|██████████████████▋                           | 537/1326 [02:38<03:51,  3.41it/s]

 41%|██████████████████▋                           | 538/1326 [02:38<03:51,  3.41it/s]

 41%|██████████████████▋                           | 539/1326 [02:38<03:51,  3.41it/s]

 41%|██████████████████▋                           | 540/1326 [02:39<03:50,  3.40it/s]

 41%|██████████████████▊                           | 541/1326 [02:39<03:50,  3.40it/s]

 41%|██████████████████▊                           | 542/1326 [02:39<03:50,  3.40it/s]

 41%|██████████████████▊                           | 543/1326 [02:40<03:49,  3.40it/s]

 41%|██████████████████▊                           | 544/1326 [02:40<03:49,  3.40it/s]

 41%|██████████████████▉                           | 545/1326 [02:40<03:49,  3.40it/s]

 41%|██████████████████▉                           | 546/1326 [02:40<03:49,  3.40it/s]

 41%|██████████████████▉                           | 547/1326 [02:41<03:48,  3.40it/s]

 41%|███████████████████                           | 548/1326 [02:41<03:48,  3.40it/s]

 41%|███████████████████                           | 549/1326 [02:41<03:48,  3.41it/s]

 41%|███████████████████                           | 550/1326 [02:42<03:47,  3.41it/s]

 42%|███████████████████                           | 551/1326 [02:42<03:47,  3.40it/s]

 42%|███████████████████▏                          | 552/1326 [02:42<03:47,  3.41it/s]

 42%|███████████████████▏                          | 553/1326 [02:42<03:47,  3.41it/s]

 42%|███████████████████▏                          | 554/1326 [02:43<03:46,  3.40it/s]

 42%|███████████████████▎                          | 555/1326 [02:43<03:46,  3.40it/s]

 42%|███████████████████▎                          | 556/1326 [02:43<03:46,  3.40it/s]

 42%|███████████████████▎                          | 557/1326 [02:44<03:45,  3.40it/s]

 42%|███████████████████▎                          | 558/1326 [02:44<03:45,  3.40it/s]

 42%|███████████████████▍                          | 559/1326 [02:44<03:45,  3.40it/s]

 42%|███████████████████▍                          | 560/1326 [02:45<03:45,  3.40it/s]

 42%|███████████████████▍                          | 561/1326 [02:45<03:44,  3.40it/s]

 42%|███████████████████▍                          | 562/1326 [02:45<03:44,  3.40it/s]

 42%|███████████████████▌                          | 563/1326 [02:45<03:44,  3.40it/s]

 43%|███████████████████▌                          | 564/1326 [02:46<03:43,  3.40it/s]

 43%|███████████████████▌                          | 565/1326 [02:46<03:43,  3.40it/s]

 43%|███████████████████▋                          | 566/1326 [02:46<03:43,  3.40it/s]

 43%|███████████████████▋                          | 567/1326 [02:47<03:42,  3.40it/s]

 43%|███████████████████▋                          | 568/1326 [02:47<03:42,  3.40it/s]

 43%|███████████████████▋                          | 569/1326 [02:47<03:42,  3.40it/s]

 43%|███████████████████▊                          | 570/1326 [02:47<03:42,  3.40it/s]

 43%|███████████████████▊                          | 571/1326 [02:48<03:41,  3.40it/s]

 43%|███████████████████▊                          | 572/1326 [02:48<03:41,  3.40it/s]

 43%|███████████████████▉                          | 573/1326 [02:48<03:41,  3.40it/s]

 43%|███████████████████▉                          | 574/1326 [02:49<03:40,  3.40it/s]

 43%|███████████████████▉                          | 575/1326 [02:49<03:40,  3.40it/s]

 43%|███████████████████▉                          | 576/1326 [02:49<03:40,  3.40it/s]

 44%|████████████████████                          | 577/1326 [02:50<03:40,  3.40it/s]

 44%|████████████████████                          | 578/1326 [02:50<03:39,  3.40it/s]

 44%|████████████████████                          | 579/1326 [02:50<03:39,  3.40it/s]

 44%|████████████████████                          | 580/1326 [02:50<03:39,  3.40it/s]

 44%|████████████████████▏                         | 581/1326 [02:51<03:38,  3.40it/s]

 44%|████████████████████▏                         | 582/1326 [02:51<03:38,  3.40it/s]

 44%|████████████████████▏                         | 583/1326 [02:51<03:38,  3.40it/s]

 44%|████████████████████▎                         | 584/1326 [02:52<03:38,  3.40it/s]

 44%|████████████████████▎                         | 585/1326 [02:52<03:37,  3.40it/s]

 44%|████████████████████▎                         | 586/1326 [02:52<03:37,  3.40it/s]

 44%|████████████████████▎                         | 587/1326 [02:52<03:37,  3.40it/s]

 44%|████████████████████▍                         | 588/1326 [02:53<03:36,  3.40it/s]

 44%|████████████████████▍                         | 589/1326 [02:53<03:36,  3.40it/s]

 44%|████████████████████▍                         | 590/1326 [02:53<03:36,  3.40it/s]

 45%|████████████████████▌                         | 591/1326 [02:54<03:36,  3.40it/s]

 45%|████████████████████▌                         | 592/1326 [02:54<03:35,  3.40it/s]

 45%|████████████████████▌                         | 593/1326 [02:54<03:35,  3.40it/s]

 45%|████████████████████▌                         | 594/1326 [02:55<03:35,  3.40it/s]

 45%|████████████████████▋                         | 595/1326 [02:55<03:34,  3.40it/s]

 45%|████████████████████▋                         | 596/1326 [02:55<03:34,  3.40it/s]

 45%|████████████████████▋                         | 597/1326 [02:55<03:34,  3.40it/s]

 45%|████████████████████▋                         | 598/1326 [02:56<03:34,  3.40it/s]

 45%|████████████████████▊                         | 599/1326 [02:56<03:33,  3.40it/s]

 45%|████████████████████▊                         | 600/1326 [02:56<03:33,  3.40it/s]

 45%|████████████████████▊                         | 601/1326 [02:57<03:33,  3.40it/s]

 45%|████████████████████▉                         | 602/1326 [02:57<03:32,  3.40it/s]

 45%|████████████████████▉                         | 603/1326 [02:57<03:32,  3.40it/s]

 46%|████████████████████▉                         | 604/1326 [02:57<03:32,  3.40it/s]

 46%|████████████████████▉                         | 605/1326 [02:58<03:31,  3.40it/s]

 46%|█████████████████████                         | 606/1326 [02:58<03:31,  3.40it/s]

 46%|█████████████████████                         | 607/1326 [02:58<03:31,  3.40it/s]

 46%|█████████████████████                         | 608/1326 [02:59<03:30,  3.40it/s]

 46%|█████████████████████▏                        | 609/1326 [02:59<03:30,  3.40it/s]

 46%|█████████████████████▏                        | 610/1326 [02:59<03:30,  3.40it/s]

 46%|█████████████████████▏                        | 611/1326 [03:00<03:30,  3.40it/s]

 46%|█████████████████████▏                        | 612/1326 [03:00<03:29,  3.40it/s]

 46%|█████████████████████▎                        | 613/1326 [03:00<03:29,  3.40it/s]

 46%|█████████████████████▎                        | 614/1326 [03:00<03:29,  3.40it/s]

 46%|█████████████████████▎                        | 615/1326 [03:01<03:28,  3.40it/s]

 46%|█████████████████████▎                        | 616/1326 [03:01<03:28,  3.40it/s]

 47%|█████████████████████▍                        | 617/1326 [03:01<03:28,  3.40it/s]

 47%|█████████████████████▍                        | 618/1326 [03:02<03:28,  3.40it/s]

 47%|█████████████████████▍                        | 619/1326 [03:02<03:27,  3.40it/s]

 47%|█████████████████████▌                        | 620/1326 [03:02<03:27,  3.40it/s]

 47%|█████████████████████▌                        | 621/1326 [03:02<03:27,  3.40it/s]

 47%|█████████████████████▌                        | 622/1326 [03:03<03:26,  3.40it/s]

 47%|█████████████████████▌                        | 623/1326 [03:03<03:26,  3.40it/s]

 47%|█████████████████████▋                        | 624/1326 [03:03<03:26,  3.40it/s]

 47%|█████████████████████▋                        | 625/1326 [03:04<03:25,  3.40it/s]

 47%|█████████████████████▋                        | 626/1326 [03:04<03:25,  3.40it/s]

 47%|█████████████████████▊                        | 627/1326 [03:04<03:25,  3.40it/s]

 47%|█████████████████████▊                        | 628/1326 [03:05<03:25,  3.40it/s]

 47%|█████████████████████▊                        | 629/1326 [03:05<03:24,  3.40it/s]

 48%|█████████████████████▊                        | 630/1326 [03:05<03:24,  3.40it/s]

 48%|█████████████████████▉                        | 631/1326 [03:05<03:24,  3.40it/s]

 48%|█████████████████████▉                        | 632/1326 [03:06<03:23,  3.40it/s]

 48%|█████████████████████▉                        | 633/1326 [03:06<03:23,  3.40it/s]

 48%|█████████████████████▉                        | 634/1326 [03:06<03:23,  3.40it/s]

 48%|██████████████████████                        | 635/1326 [03:07<03:22,  3.40it/s]

 48%|██████████████████████                        | 636/1326 [03:07<03:22,  3.40it/s]

 48%|██████████████████████                        | 637/1326 [03:07<03:22,  3.40it/s]

 48%|██████████████████████▏                       | 638/1326 [03:07<03:22,  3.41it/s]

 48%|██████████████████████▏                       | 639/1326 [03:08<03:21,  3.40it/s]

 48%|██████████████████████▏                       | 640/1326 [03:08<03:21,  3.40it/s]

 48%|██████████████████████▏                       | 641/1326 [03:08<03:21,  3.40it/s]

 48%|██████████████████████▎                       | 642/1326 [03:09<03:20,  3.40it/s]

 48%|██████████████████████▎                       | 643/1326 [03:09<03:20,  3.40it/s]

 49%|██████████████████████▎                       | 644/1326 [03:09<03:20,  3.40it/s]

 49%|██████████████████████▍                       | 645/1326 [03:10<03:20,  3.40it/s]

 49%|██████████████████████▍                       | 646/1326 [03:10<03:19,  3.40it/s]

 49%|██████████████████████▍                       | 647/1326 [03:10<03:19,  3.40it/s]

 49%|██████████████████████▍                       | 648/1326 [03:10<03:19,  3.40it/s]

 49%|██████████████████████▌                       | 649/1326 [03:11<03:18,  3.40it/s]

 49%|██████████████████████▌                       | 650/1326 [03:11<03:18,  3.40it/s]

 49%|██████████████████████▌                       | 651/1326 [03:11<03:18,  3.40it/s]

 49%|██████████████████████▌                       | 652/1326 [03:12<03:18,  3.40it/s]

 49%|██████████████████████▋                       | 653/1326 [03:12<03:17,  3.40it/s]

 49%|██████████████████████▋                       | 654/1326 [03:12<03:17,  3.40it/s]

 49%|██████████████████████▋                       | 655/1326 [03:12<03:17,  3.40it/s]

 49%|██████████████████████▊                       | 656/1326 [03:13<03:16,  3.40it/s]

 50%|██████████████████████▊                       | 657/1326 [03:13<03:16,  3.40it/s]

 50%|██████████████████████▊                       | 658/1326 [03:13<03:16,  3.40it/s]

 50%|██████████████████████▊                       | 659/1326 [03:14<03:16,  3.40it/s]

 50%|██████████████████████▉                       | 660/1326 [03:14<03:15,  3.40it/s]

 50%|██████████████████████▉                       | 661/1326 [03:14<03:15,  3.40it/s]

 50%|██████████████████████▉                       | 662/1326 [03:15<03:15,  3.40it/s]

 50%|███████████████████████                       | 663/1326 [03:15<03:14,  3.40it/s]

 50%|███████████████████████                       | 664/1326 [03:15<03:14,  3.40it/s]

 50%|███████████████████████                       | 665/1326 [03:15<03:14,  3.40it/s]

 50%|███████████████████████                       | 666/1326 [03:16<03:13,  3.40it/s]

 50%|███████████████████████▏                      | 667/1326 [03:16<03:13,  3.40it/s]

 50%|███████████████████████▏                      | 668/1326 [03:16<03:13,  3.40it/s]

 50%|███████████████████████▏                      | 669/1326 [03:17<03:13,  3.40it/s]

 51%|███████████████████████▏                      | 670/1326 [03:17<03:12,  3.40it/s]

 51%|███████████████████████▎                      | 671/1326 [03:17<03:12,  3.40it/s]

 51%|███████████████████████▎                      | 672/1326 [03:17<03:12,  3.40it/s]

 51%|███████████████████████▎                      | 673/1326 [03:18<03:11,  3.40it/s]

 51%|███████████████████████▍                      | 674/1326 [03:18<03:11,  3.40it/s]

 51%|███████████████████████▍                      | 675/1326 [03:18<03:11,  3.40it/s]

 51%|███████████████████████▍                      | 676/1326 [03:19<03:11,  3.40it/s]

 51%|███████████████████████▍                      | 677/1326 [03:19<03:10,  3.40it/s]

 51%|███████████████████████▌                      | 678/1326 [03:19<03:10,  3.40it/s]

 51%|███████████████████████▌                      | 679/1326 [03:20<03:10,  3.40it/s]

 51%|███████████████████████▌                      | 680/1326 [03:20<03:09,  3.40it/s]

 51%|███████████████████████▌                      | 681/1326 [03:20<03:09,  3.40it/s]

 51%|███████████████████████▋                      | 682/1326 [03:20<03:09,  3.40it/s]

 52%|███████████████████████▋                      | 683/1326 [03:21<03:08,  3.40it/s]

 52%|███████████████████████▋                      | 684/1326 [03:21<03:08,  3.40it/s]

 52%|███████████████████████▊                      | 685/1326 [03:21<03:08,  3.40it/s]

 52%|███████████████████████▊                      | 686/1326 [03:22<03:08,  3.40it/s]

 52%|███████████████████████▊                      | 687/1326 [03:22<03:07,  3.40it/s]

 52%|███████████████████████▊                      | 688/1326 [03:22<03:07,  3.40it/s]

 52%|███████████████████████▉                      | 689/1326 [03:22<03:07,  3.40it/s]

 52%|███████████████████████▉                      | 690/1326 [03:23<03:06,  3.40it/s]

 52%|███████████████████████▉                      | 691/1326 [03:23<03:06,  3.40it/s]

 52%|████████████████████████                      | 692/1326 [03:23<03:06,  3.40it/s]

 52%|████████████████████████                      | 693/1326 [03:24<03:06,  3.40it/s]

 52%|████████████████████████                      | 694/1326 [03:24<03:05,  3.40it/s]

 52%|████████████████████████                      | 695/1326 [03:24<03:05,  3.40it/s]

 52%|████████████████████████▏                     | 696/1326 [03:25<03:05,  3.40it/s]

 53%|████████████████████████▏                     | 697/1326 [03:25<03:04,  3.40it/s]

 53%|████████████████████████▏                     | 698/1326 [03:25<03:04,  3.40it/s]

 53%|████████████████████████▏                     | 699/1326 [03:25<03:04,  3.40it/s]

 53%|████████████████████████▎                     | 700/1326 [03:26<03:03,  3.40it/s]

 53%|████████████████████████▎                     | 701/1326 [03:26<03:03,  3.40it/s]

 53%|████████████████████████▎                     | 702/1326 [03:26<03:03,  3.40it/s]

 53%|████████████████████████▍                     | 703/1326 [03:27<03:03,  3.40it/s]

 53%|████████████████████████▍                     | 704/1326 [03:27<03:02,  3.40it/s]

 53%|████████████████████████▍                     | 705/1326 [03:27<03:02,  3.40it/s]

 53%|████████████████████████▍                     | 706/1326 [03:27<03:02,  3.40it/s]

 53%|████████████████████████▌                     | 707/1326 [03:28<03:01,  3.40it/s]

 53%|████████████████████████▌                     | 708/1326 [03:28<03:01,  3.40it/s]

 53%|████████████████████████▌                     | 709/1326 [03:28<03:01,  3.40it/s]

 54%|████████████████████████▋                     | 710/1326 [03:29<03:01,  3.40it/s]

 54%|████████████████████████▋                     | 711/1326 [03:29<03:00,  3.40it/s]

 54%|████████████████████████▋                     | 712/1326 [03:29<03:00,  3.40it/s]

 54%|████████████████████████▋                     | 713/1326 [03:29<03:00,  3.40it/s]

 54%|████████████████████████▊                     | 714/1326 [03:30<02:59,  3.40it/s]

 54%|████████████████████████▊                     | 715/1326 [03:30<02:59,  3.40it/s]

 54%|████████████████████████▊                     | 716/1326 [03:30<02:59,  3.40it/s]

 54%|████████████████████████▊                     | 717/1326 [03:31<02:59,  3.40it/s]

 54%|████████████████████████▉                     | 718/1326 [03:31<02:58,  3.40it/s]

 54%|████████████████████████▉                     | 719/1326 [03:31<02:58,  3.40it/s]

 54%|████████████████████████▉                     | 720/1326 [03:32<02:58,  3.40it/s]

 54%|█████████████████████████                     | 721/1326 [03:32<02:57,  3.40it/s]

 54%|█████████████████████████                     | 722/1326 [03:32<02:57,  3.40it/s]

 55%|█████████████████████████                     | 723/1326 [03:32<02:57,  3.40it/s]

 55%|█████████████████████████                     | 724/1326 [03:33<02:56,  3.40it/s]

 55%|█████████████████████████▏                    | 725/1326 [03:33<02:56,  3.40it/s]

 55%|█████████████████████████▏                    | 726/1326 [03:33<02:56,  3.40it/s]

 55%|█████████████████████████▏                    | 727/1326 [03:34<02:56,  3.40it/s]

 55%|█████████████████████████▎                    | 728/1326 [03:34<02:55,  3.40it/s]

 55%|█████████████████████████▎                    | 729/1326 [03:34<02:55,  3.40it/s]

 55%|█████████████████████████▎                    | 730/1326 [03:34<02:55,  3.40it/s]

 55%|█████████████████████████▎                    | 731/1326 [03:35<02:54,  3.40it/s]

 55%|█████████████████████████▍                    | 732/1326 [03:35<02:54,  3.40it/s]

 55%|█████████████████████████▍                    | 733/1326 [03:35<02:54,  3.40it/s]

 55%|█████████████████████████▍                    | 734/1326 [03:36<02:54,  3.40it/s]

 55%|█████████████████████████▍                    | 735/1326 [03:36<02:53,  3.40it/s]

 56%|█████████████████████████▌                    | 736/1326 [03:36<02:53,  3.40it/s]

 56%|█████████████████████████▌                    | 737/1326 [03:37<02:53,  3.40it/s]

 56%|█████████████████████████▌                    | 738/1326 [03:37<02:52,  3.40it/s]

 56%|█████████████████████████▋                    | 739/1326 [03:37<02:52,  3.40it/s]

 56%|█████████████████████████▋                    | 740/1326 [03:37<02:52,  3.40it/s]

 56%|█████████████████████████▋                    | 741/1326 [03:38<02:51,  3.40it/s]

 56%|█████████████████████████▋                    | 742/1326 [03:38<02:51,  3.40it/s]

 56%|█████████████████████████▊                    | 743/1326 [03:38<02:51,  3.40it/s]

 56%|█████████████████████████▊                    | 744/1326 [03:39<02:51,  3.40it/s]

 56%|█████████████████████████▊                    | 745/1326 [03:39<02:50,  3.40it/s]

 56%|█████████████████████████▉                    | 746/1326 [03:39<02:50,  3.40it/s]

 56%|█████████████████████████▉                    | 747/1326 [03:39<02:50,  3.40it/s]

 56%|█████████████████████████▉                    | 748/1326 [03:40<02:49,  3.40it/s]

 56%|█████████████████████████▉                    | 749/1326 [03:40<02:49,  3.40it/s]

 57%|██████████████████████████                    | 750/1326 [03:40<02:49,  3.40it/s]

 57%|██████████████████████████                    | 751/1326 [03:41<02:48,  3.40it/s]

 57%|██████████████████████████                    | 752/1326 [03:41<02:48,  3.40it/s]

 57%|██████████████████████████                    | 753/1326 [03:41<02:48,  3.40it/s]

 57%|██████████████████████████▏                   | 754/1326 [03:42<02:48,  3.40it/s]

 57%|██████████████████████████▏                   | 755/1326 [03:42<02:47,  3.40it/s]

 57%|██████████████████████████▏                   | 756/1326 [03:42<02:47,  3.40it/s]

 57%|██████████████████████████▎                   | 757/1326 [03:42<02:47,  3.40it/s]

 57%|██████████████████████████▎                   | 758/1326 [03:43<02:47,  3.40it/s]

 57%|██████████████████████████▎                   | 759/1326 [03:43<02:46,  3.40it/s]

 57%|██████████████████████████▎                   | 760/1326 [03:43<02:46,  3.40it/s]

 57%|██████████████████████████▍                   | 761/1326 [03:44<02:46,  3.40it/s]

 57%|██████████████████████████▍                   | 762/1326 [03:44<02:45,  3.40it/s]

 58%|██████████████████████████▍                   | 763/1326 [03:44<02:45,  3.40it/s]

 58%|██████████████████████████▌                   | 764/1326 [03:44<02:45,  3.40it/s]

 58%|██████████████████████████▌                   | 765/1326 [03:45<02:44,  3.40it/s]

 58%|██████████████████████████▌                   | 766/1326 [03:45<02:44,  3.40it/s]

 58%|██████████████████████████▌                   | 767/1326 [03:45<02:44,  3.40it/s]

 58%|██████████████████████████▋                   | 768/1326 [03:46<02:43,  3.40it/s]

 58%|██████████████████████████▋                   | 769/1326 [03:46<02:43,  3.40it/s]

 58%|██████████████████████████▋                   | 770/1326 [03:46<02:43,  3.40it/s]

 58%|██████████████████████████▋                   | 771/1326 [03:47<02:43,  3.40it/s]

 58%|██████████████████████████▊                   | 772/1326 [03:47<02:42,  3.40it/s]

 58%|██████████████████████████▊                   | 773/1326 [03:47<02:42,  3.40it/s]

 58%|██████████████████████████▊                   | 774/1326 [03:47<02:42,  3.40it/s]

 58%|██████████████████████████▉                   | 775/1326 [03:48<02:41,  3.40it/s]

 59%|██████████████████████████▉                   | 776/1326 [03:48<02:41,  3.40it/s]

 59%|██████████████████████████▉                   | 777/1326 [03:48<02:41,  3.40it/s]

 59%|██████████████████████████▉                   | 778/1326 [03:49<02:41,  3.40it/s]

 59%|███████████████████████████                   | 779/1326 [03:49<02:40,  3.40it/s]

 59%|███████████████████████████                   | 780/1326 [03:49<02:40,  3.40it/s]

 59%|███████████████████████████                   | 781/1326 [03:49<02:40,  3.40it/s]

 59%|███████████████████████████▏                  | 782/1326 [03:50<02:39,  3.40it/s]

 59%|███████████████████████████▏                  | 783/1326 [03:50<02:39,  3.40it/s]

 59%|███████████████████████████▏                  | 784/1326 [03:50<02:39,  3.40it/s]

 59%|███████████████████████████▏                  | 785/1326 [03:51<02:39,  3.40it/s]

 59%|███████████████████████████▎                  | 786/1326 [03:51<02:38,  3.40it/s]

 59%|███████████████████████████▎                  | 787/1326 [03:51<02:38,  3.40it/s]

 59%|███████████████████████████▎                  | 788/1326 [03:52<02:38,  3.40it/s]

 60%|███████████████████████████▎                  | 789/1326 [03:52<02:37,  3.40it/s]

 60%|███████████████████████████▍                  | 790/1326 [03:52<02:37,  3.40it/s]

 60%|███████████████████████████▍                  | 791/1326 [03:52<02:37,  3.40it/s]

 60%|███████████████████████████▍                  | 792/1326 [03:53<02:36,  3.40it/s]

 60%|███████████████████████████▌                  | 793/1326 [03:53<02:36,  3.40it/s]

 60%|███████████████████████████▌                  | 794/1326 [03:53<02:36,  3.40it/s]

 60%|███████████████████████████▌                  | 795/1326 [03:54<02:36,  3.40it/s]

 60%|███████████████████████████▌                  | 796/1326 [03:54<02:35,  3.40it/s]

 60%|███████████████████████████▋                  | 797/1326 [03:54<02:35,  3.40it/s]

 60%|███████████████████████████▋                  | 798/1326 [03:54<02:35,  3.40it/s]

 60%|███████████████████████████▋                  | 799/1326 [03:55<02:34,  3.40it/s]

 60%|███████████████████████████▊                  | 800/1326 [03:55<02:34,  3.40it/s]

 60%|███████████████████████████▊                  | 801/1326 [03:55<02:34,  3.40it/s]

 60%|███████████████████████████▊                  | 802/1326 [03:56<02:34,  3.40it/s]

 61%|███████████████████████████▊                  | 803/1326 [03:56<02:33,  3.40it/s]

 61%|███████████████████████████▉                  | 804/1326 [03:56<02:33,  3.40it/s]

 61%|███████████████████████████▉                  | 805/1326 [03:57<02:33,  3.40it/s]

 61%|███████████████████████████▉                  | 806/1326 [03:57<02:32,  3.40it/s]

 61%|███████████████████████████▉                  | 807/1326 [03:57<02:32,  3.40it/s]

 61%|████████████████████████████                  | 808/1326 [03:57<02:32,  3.40it/s]

 61%|████████████████████████████                  | 809/1326 [03:58<02:31,  3.40it/s]

 61%|████████████████████████████                  | 810/1326 [03:58<02:31,  3.40it/s]

 61%|████████████████████████████▏                 | 811/1326 [03:58<02:31,  3.40it/s]

 61%|████████████████████████████▏                 | 812/1326 [03:59<02:31,  3.40it/s]

 61%|████████████████████████████▏                 | 813/1326 [03:59<02:30,  3.40it/s]

 61%|████████████████████████████▏                 | 814/1326 [03:59<02:30,  3.40it/s]

 61%|████████████████████████████▎                 | 815/1326 [03:59<02:30,  3.40it/s]

 62%|████████████████████████████▎                 | 816/1326 [04:00<02:29,  3.40it/s]

 62%|████████████████████████████▎                 | 817/1326 [04:00<02:29,  3.40it/s]

 62%|████████████████████████████▍                 | 818/1326 [04:00<02:29,  3.40it/s]

 62%|████████████████████████████▍                 | 819/1326 [04:01<02:28,  3.40it/s]

 62%|████████████████████████████▍                 | 820/1326 [04:01<02:28,  3.40it/s]

 62%|████████████████████████████▍                 | 821/1326 [04:01<02:28,  3.40it/s]

 62%|████████████████████████████▌                 | 822/1326 [04:02<02:28,  3.40it/s]

 62%|████████████████████████████▌                 | 823/1326 [04:02<02:27,  3.40it/s]

 62%|████████████████████████████▌                 | 824/1326 [04:02<02:27,  3.40it/s]

 62%|████████████████████████████▌                 | 825/1326 [04:02<02:27,  3.40it/s]

 62%|████████████████████████████▋                 | 826/1326 [04:03<02:26,  3.40it/s]

 62%|████████████████████████████▋                 | 827/1326 [04:03<02:26,  3.40it/s]

 62%|████████████████████████████▋                 | 828/1326 [04:03<02:26,  3.40it/s]

 63%|████████████████████████████▊                 | 829/1326 [04:04<02:26,  3.40it/s]

 63%|████████████████████████████▊                 | 830/1326 [04:04<02:25,  3.40it/s]

 63%|████████████████████████████▊                 | 831/1326 [04:04<02:25,  3.40it/s]

 63%|████████████████████████████▊                 | 832/1326 [04:04<02:25,  3.40it/s]

 63%|████████████████████████████▉                 | 833/1326 [04:05<02:24,  3.40it/s]

 63%|████████████████████████████▉                 | 834/1326 [04:05<02:24,  3.40it/s]

 63%|████████████████████████████▉                 | 835/1326 [04:05<02:24,  3.40it/s]

 63%|█████████████████████████████                 | 836/1326 [04:06<02:23,  3.40it/s]

 63%|█████████████████████████████                 | 837/1326 [04:06<02:23,  3.40it/s]

 63%|█████████████████████████████                 | 838/1326 [04:06<02:23,  3.40it/s]

 63%|█████████████████████████████                 | 839/1326 [04:07<02:23,  3.40it/s]

 63%|█████████████████████████████▏                | 840/1326 [04:07<02:22,  3.40it/s]

 63%|█████████████████████████████▏                | 841/1326 [04:07<02:22,  3.40it/s]

 63%|█████████████████████████████▏                | 842/1326 [04:07<02:22,  3.40it/s]

 64%|█████████████████████████████▏                | 843/1326 [04:08<02:21,  3.40it/s]

 64%|█████████████████████████████▎                | 844/1326 [04:08<02:21,  3.40it/s]

 64%|█████████████████████████████▎                | 845/1326 [04:08<02:21,  3.40it/s]

 64%|█████████████████████████████▎                | 846/1326 [04:09<02:21,  3.40it/s]

 64%|█████████████████████████████▍                | 847/1326 [04:09<02:20,  3.40it/s]

 64%|█████████████████████████████▍                | 848/1326 [04:09<02:20,  3.40it/s]

 64%|█████████████████████████████▍                | 849/1326 [04:09<02:20,  3.40it/s]

 64%|█████████████████████████████▍                | 850/1326 [04:10<02:19,  3.40it/s]

 64%|█████████████████████████████▌                | 851/1326 [04:10<02:19,  3.40it/s]

 64%|█████████████████████████████▌                | 852/1326 [04:10<02:19,  3.40it/s]

 64%|█████████████████████████████▌                | 853/1326 [04:11<02:18,  3.40it/s]

 64%|█████████████████████████████▋                | 854/1326 [04:11<02:18,  3.40it/s]

 64%|█████████████████████████████▋                | 855/1326 [04:11<02:18,  3.40it/s]

 65%|█████████████████████████████▋                | 856/1326 [04:12<02:18,  3.40it/s]

 65%|█████████████████████████████▋                | 857/1326 [04:12<02:17,  3.40it/s]

 65%|█████████████████████████████▊                | 858/1326 [04:12<02:17,  3.40it/s]

 65%|█████████████████████████████▊                | 859/1326 [04:12<02:17,  3.40it/s]

 65%|█████████████████████████████▊                | 860/1326 [04:13<02:16,  3.40it/s]

 65%|█████████████████████████████▊                | 861/1326 [04:13<02:16,  3.40it/s]

 65%|█████████████████████████████▉                | 862/1326 [04:13<02:16,  3.40it/s]

 65%|█████████████████████████████▉                | 863/1326 [04:14<02:15,  3.40it/s]

 65%|█████████████████████████████▉                | 864/1326 [04:14<02:15,  3.40it/s]

 65%|██████████████████████████████                | 865/1326 [04:14<02:15,  3.40it/s]

 65%|██████████████████████████████                | 866/1326 [04:14<02:15,  3.40it/s]

 65%|██████████████████████████████                | 867/1326 [04:15<02:14,  3.40it/s]

 65%|██████████████████████████████                | 868/1326 [04:15<02:14,  3.40it/s]

 66%|██████████████████████████████▏               | 869/1326 [04:15<02:14,  3.40it/s]

 66%|██████████████████████████████▏               | 870/1326 [04:16<02:13,  3.40it/s]

 66%|██████████████████████████████▏               | 871/1326 [04:16<02:13,  3.40it/s]

 66%|██████████████████████████████▎               | 872/1326 [04:16<02:13,  3.40it/s]

 66%|██████████████████████████████▎               | 873/1326 [04:17<02:13,  3.41it/s]

 66%|██████████████████████████████▎               | 874/1326 [04:17<02:12,  3.41it/s]

 66%|██████████████████████████████▎               | 875/1326 [04:17<02:12,  3.40it/s]

 66%|██████████████████████████████▍               | 876/1326 [04:17<02:12,  3.41it/s]

 66%|██████████████████████████████▍               | 877/1326 [04:18<02:11,  3.41it/s]

 66%|██████████████████████████████▍               | 878/1326 [04:18<02:11,  3.41it/s]

 66%|██████████████████████████████▍               | 879/1326 [04:18<02:11,  3.41it/s]

 66%|██████████████████████████████▌               | 880/1326 [04:19<02:11,  3.40it/s]

 66%|██████████████████████████████▌               | 881/1326 [04:19<02:10,  3.40it/s]

 67%|██████████████████████████████▌               | 882/1326 [04:19<02:10,  3.40it/s]

 67%|██████████████████████████████▋               | 883/1326 [04:19<02:10,  3.40it/s]

 67%|██████████████████████████████▋               | 884/1326 [04:20<02:09,  3.40it/s]

 67%|██████████████████████████████▋               | 885/1326 [04:20<02:09,  3.40it/s]

 67%|██████████████████████████████▋               | 886/1326 [04:20<02:09,  3.40it/s]

 67%|██████████████████████████████▊               | 887/1326 [04:21<02:08,  3.40it/s]

 67%|██████████████████████████████▊               | 888/1326 [04:21<02:08,  3.40it/s]

 67%|██████████████████████████████▊               | 889/1326 [04:21<02:08,  3.40it/s]

 67%|██████████████████████████████▊               | 890/1326 [04:22<02:08,  3.40it/s]

 67%|██████████████████████████████▉               | 891/1326 [04:22<02:07,  3.40it/s]

 67%|██████████████████████████████▉               | 892/1326 [04:22<02:07,  3.40it/s]

 67%|██████████████████████████████▉               | 893/1326 [04:22<02:07,  3.40it/s]

 67%|███████████████████████████████               | 894/1326 [04:23<02:06,  3.40it/s]

 67%|███████████████████████████████               | 895/1326 [04:23<02:06,  3.40it/s]

 68%|███████████████████████████████               | 896/1326 [04:23<02:06,  3.40it/s]

 68%|███████████████████████████████               | 897/1326 [04:24<02:06,  3.40it/s]

 68%|███████████████████████████████▏              | 898/1326 [04:24<02:05,  3.40it/s]

 68%|███████████████████████████████▏              | 899/1326 [04:24<02:05,  3.40it/s]

 68%|███████████████████████████████▏              | 900/1326 [04:24<02:05,  3.40it/s]

 68%|███████████████████████████████▎              | 901/1326 [04:25<02:04,  3.40it/s]

 68%|███████████████████████████████▎              | 902/1326 [04:25<02:04,  3.40it/s]

 68%|███████████████████████████████▎              | 903/1326 [04:25<02:04,  3.40it/s]

 68%|███████████████████████████████▎              | 904/1326 [04:26<02:03,  3.40it/s]

 68%|███████████████████████████████▍              | 905/1326 [04:26<02:03,  3.41it/s]

 68%|███████████████████████████████▍              | 906/1326 [04:26<02:03,  3.40it/s]

 68%|███████████████████████████████▍              | 907/1326 [04:27<02:03,  3.40it/s]

 68%|███████████████████████████████▍              | 908/1326 [04:27<02:02,  3.40it/s]

 69%|███████████████████████████████▌              | 909/1326 [04:27<02:02,  3.40it/s]

 69%|███████████████████████████████▌              | 910/1326 [04:27<02:02,  3.40it/s]

 69%|███████████████████████████████▌              | 911/1326 [04:28<02:01,  3.40it/s]

 69%|███████████████████████████████▋              | 912/1326 [04:28<02:01,  3.41it/s]

 69%|███████████████████████████████▋              | 913/1326 [04:28<02:01,  3.40it/s]

 69%|███████████████████████████████▋              | 914/1326 [04:29<02:01,  3.40it/s]

 69%|███████████████████████████████▋              | 915/1326 [04:29<02:00,  3.40it/s]

 69%|███████████████████████████████▊              | 916/1326 [04:29<02:00,  3.40it/s]

 69%|███████████████████████████████▊              | 917/1326 [04:29<02:00,  3.40it/s]

 69%|███████████████████████████████▊              | 918/1326 [04:30<01:59,  3.41it/s]

 69%|███████████████████████████████▉              | 919/1326 [04:30<01:59,  3.41it/s]

 69%|███████████████████████████████▉              | 920/1326 [04:30<01:59,  3.41it/s]

 69%|███████████████████████████████▉              | 921/1326 [04:31<01:58,  3.40it/s]

 70%|███████████████████████████████▉              | 922/1326 [04:31<01:58,  3.41it/s]

 70%|████████████████████████████████              | 923/1326 [04:31<01:58,  3.40it/s]

 70%|████████████████████████████████              | 924/1326 [04:32<01:58,  3.40it/s]

 70%|████████████████████████████████              | 925/1326 [04:32<01:57,  3.41it/s]

 70%|████████████████████████████████              | 926/1326 [04:32<01:57,  3.41it/s]

 70%|████████████████████████████████▏             | 927/1326 [04:32<01:57,  3.41it/s]

 70%|████████████████████████████████▏             | 928/1326 [04:33<01:56,  3.41it/s]

 70%|████████████████████████████████▏             | 929/1326 [04:33<01:56,  3.41it/s]

 70%|████████████████████████████████▎             | 930/1326 [04:33<01:56,  3.40it/s]

 70%|████████████████████████████████▎             | 931/1326 [04:34<01:56,  3.40it/s]

 70%|████████████████████████████████▎             | 932/1326 [04:34<01:55,  3.40it/s]

 70%|████████████████████████████████▎             | 933/1326 [04:34<01:55,  3.40it/s]

 70%|████████████████████████████████▍             | 934/1326 [04:34<01:55,  3.40it/s]

 71%|████████████████████████████████▍             | 935/1326 [04:35<01:54,  3.40it/s]

 71%|████████████████████████████████▍             | 936/1326 [04:35<01:54,  3.40it/s]

 71%|████████████████████████████████▌             | 937/1326 [04:35<01:54,  3.41it/s]

 71%|████████████████████████████████▌             | 938/1326 [04:36<01:53,  3.41it/s]

 71%|████████████████████████████████▌             | 939/1326 [04:36<01:53,  3.40it/s]

 71%|████████████████████████████████▌             | 940/1326 [04:36<01:53,  3.40it/s]

 71%|████████████████████████████████▋             | 941/1326 [04:36<01:53,  3.41it/s]

 71%|████████████████████████████████▋             | 942/1326 [04:37<01:52,  3.40it/s]

 71%|████████████████████████████████▋             | 943/1326 [04:37<01:52,  3.40it/s]

 71%|████████████████████████████████▋             | 944/1326 [04:37<01:52,  3.40it/s]

 71%|████████████████████████████████▊             | 945/1326 [04:38<01:51,  3.40it/s]

 71%|████████████████████████████████▊             | 946/1326 [04:38<01:51,  3.40it/s]

 71%|████████████████████████████████▊             | 947/1326 [04:38<01:51,  3.40it/s]

 71%|████████████████████████████████▉             | 948/1326 [04:39<01:51,  3.40it/s]

 72%|████████████████████████████████▉             | 949/1326 [04:39<01:50,  3.40it/s]

 72%|████████████████████████████████▉             | 950/1326 [04:39<01:50,  3.40it/s]

 72%|████████████████████████████████▉             | 951/1326 [04:39<01:50,  3.40it/s]

 72%|█████████████████████████████████             | 952/1326 [04:40<01:49,  3.40it/s]

 72%|█████████████████████████████████             | 953/1326 [04:40<01:49,  3.40it/s]

 72%|█████████████████████████████████             | 954/1326 [04:40<01:49,  3.41it/s]

 72%|█████████████████████████████████▏            | 955/1326 [04:41<01:48,  3.40it/s]

 72%|█████████████████████████████████▏            | 956/1326 [04:41<01:48,  3.40it/s]

 72%|█████████████████████████████████▏            | 957/1326 [04:41<01:48,  3.41it/s]

 72%|█████████████████████████████████▏            | 958/1326 [04:41<01:48,  3.41it/s]

 72%|█████████████████████████████████▎            | 959/1326 [04:42<01:47,  3.41it/s]

 72%|█████████████████████████████████▎            | 960/1326 [04:42<01:47,  3.41it/s]

 72%|█████████████████████████████████▎            | 961/1326 [04:42<01:47,  3.40it/s]

 73%|█████████████████████████████████▎            | 962/1326 [04:43<01:46,  3.40it/s]

 73%|█████████████████████████████████▍            | 963/1326 [04:43<01:46,  3.40it/s]

 73%|█████████████████████████████████▍            | 964/1326 [04:43<01:46,  3.40it/s]

 73%|█████████████████████████████████▍            | 965/1326 [04:44<01:46,  3.40it/s]

 73%|█████████████████████████████████▌            | 966/1326 [04:44<01:45,  3.40it/s]

 73%|█████████████████████████████████▌            | 967/1326 [04:44<01:45,  3.40it/s]

 73%|█████████████████████████████████▌            | 968/1326 [04:44<01:45,  3.40it/s]

 73%|█████████████████████████████████▌            | 969/1326 [04:45<01:44,  3.40it/s]

 73%|█████████████████████████████████▋            | 970/1326 [04:45<01:44,  3.40it/s]

 73%|█████████████████████████████████▋            | 971/1326 [04:45<01:44,  3.40it/s]

 73%|█████████████████████████████████▋            | 972/1326 [04:46<01:44,  3.40it/s]

 73%|█████████████████████████████████▊            | 973/1326 [04:46<01:43,  3.40it/s]

 73%|█████████████████████████████████▊            | 974/1326 [04:46<01:43,  3.40it/s]

 74%|█████████████████████████████████▊            | 975/1326 [04:46<01:43,  3.40it/s]

 74%|█████████████████████████████████▊            | 976/1326 [04:47<01:42,  3.40it/s]

 74%|█████████████████████████████████▉            | 977/1326 [04:47<01:42,  3.40it/s]

 74%|█████████████████████████████████▉            | 978/1326 [04:47<01:42,  3.40it/s]

 74%|█████████████████████████████████▉            | 979/1326 [04:48<01:41,  3.40it/s]

 74%|█████████████████████████████████▉            | 980/1326 [04:48<01:41,  3.40it/s]

 74%|██████████████████████████████████            | 981/1326 [04:48<01:41,  3.40it/s]

 74%|██████████████████████████████████            | 982/1326 [04:49<01:41,  3.40it/s]

 74%|██████████████████████████████████            | 983/1326 [04:49<01:40,  3.40it/s]

 74%|██████████████████████████████████▏           | 984/1326 [04:49<01:40,  3.40it/s]

 74%|██████████████████████████████████▏           | 985/1326 [04:49<01:40,  3.40it/s]

 74%|██████████████████████████████████▏           | 986/1326 [04:50<01:39,  3.40it/s]

 74%|██████████████████████████████████▏           | 987/1326 [04:50<01:39,  3.40it/s]

 75%|██████████████████████████████████▎           | 988/1326 [04:50<01:39,  3.40it/s]

 75%|██████████████████████████████████▎           | 989/1326 [04:51<01:38,  3.40it/s]

 75%|██████████████████████████████████▎           | 990/1326 [04:51<01:38,  3.41it/s]

 75%|██████████████████████████████████▍           | 991/1326 [04:51<01:38,  3.40it/s]

 75%|██████████████████████████████████▍           | 992/1326 [04:51<01:38,  3.40it/s]

 75%|██████████████████████████████████▍           | 993/1326 [04:52<01:37,  3.40it/s]

 75%|██████████████████████████████████▍           | 994/1326 [04:52<01:37,  3.40it/s]

 75%|██████████████████████████████████▌           | 995/1326 [04:52<01:37,  3.40it/s]

 75%|██████████████████████████████████▌           | 996/1326 [04:53<01:36,  3.40it/s]

 75%|██████████████████████████████████▌           | 997/1326 [04:53<01:36,  3.40it/s]

 75%|██████████████████████████████████▌           | 998/1326 [04:53<01:36,  3.40it/s]

 75%|██████████████████████████████████▋           | 999/1326 [04:54<01:36,  3.40it/s]

 75%|█████████████████████████████████▉           | 1000/1326 [04:54<01:35,  3.40it/s]

 75%|█████████████████████████████████▉           | 1001/1326 [04:54<01:35,  3.40it/s]

 76%|██████████████████████████████████           | 1002/1326 [04:54<01:35,  3.40it/s]

 76%|██████████████████████████████████           | 1003/1326 [04:55<01:34,  3.40it/s]

 76%|██████████████████████████████████           | 1004/1326 [04:55<01:34,  3.40it/s]

 76%|██████████████████████████████████           | 1005/1326 [04:55<01:34,  3.40it/s]

 76%|██████████████████████████████████▏          | 1006/1326 [04:56<01:33,  3.41it/s]

 76%|██████████████████████████████████▏          | 1007/1326 [04:56<01:33,  3.41it/s]

 76%|██████████████████████████████████▏          | 1008/1326 [04:56<01:33,  3.41it/s]

 76%|██████████████████████████████████▏          | 1009/1326 [04:56<01:33,  3.41it/s]

 76%|██████████████████████████████████▎          | 1010/1326 [04:57<01:32,  3.41it/s]

 76%|██████████████████████████████████▎          | 1011/1326 [04:57<01:32,  3.40it/s]

 76%|██████████████████████████████████▎          | 1012/1326 [04:57<01:32,  3.41it/s]

 76%|██████████████████████████████████▍          | 1013/1326 [04:58<01:31,  3.41it/s]

 76%|██████████████████████████████████▍          | 1014/1326 [04:58<01:31,  3.41it/s]

 77%|██████████████████████████████████▍          | 1015/1326 [04:58<01:31,  3.40it/s]

 77%|██████████████████████████████████▍          | 1016/1326 [04:59<01:31,  3.41it/s]

 77%|██████████████████████████████████▌          | 1017/1326 [04:59<01:30,  3.40it/s]

 77%|██████████████████████████████████▌          | 1018/1326 [04:59<01:30,  3.40it/s]

 77%|██████████████████████████████████▌          | 1019/1326 [04:59<01:30,  3.40it/s]

 77%|██████████████████████████████████▌          | 1020/1326 [05:00<01:29,  3.40it/s]

 77%|██████████████████████████████████▋          | 1021/1326 [05:00<01:29,  3.40it/s]

 77%|██████████████████████████████████▋          | 1022/1326 [05:00<01:29,  3.40it/s]

 77%|██████████████████████████████████▋          | 1023/1326 [05:01<01:29,  3.40it/s]

 77%|██████████████████████████████████▊          | 1024/1326 [05:01<01:28,  3.40it/s]

 77%|██████████████████████████████████▊          | 1025/1326 [05:01<01:28,  3.40it/s]

 77%|██████████████████████████████████▊          | 1026/1326 [05:01<01:28,  3.40it/s]

 77%|██████████████████████████████████▊          | 1027/1326 [05:02<01:27,  3.40it/s]

 78%|██████████████████████████████████▉          | 1028/1326 [05:02<01:27,  3.40it/s]

 78%|██████████████████████████████████▉          | 1029/1326 [05:02<01:27,  3.40it/s]

 78%|██████████████████████████████████▉          | 1030/1326 [05:03<01:26,  3.40it/s]

 78%|██████████████████████████████████▉          | 1031/1326 [05:03<01:26,  3.40it/s]

 78%|███████████████████████████████████          | 1032/1326 [05:03<01:26,  3.40it/s]

 78%|███████████████████████████████████          | 1033/1326 [05:04<01:26,  3.40it/s]

 78%|███████████████████████████████████          | 1034/1326 [05:04<01:25,  3.40it/s]

 78%|███████████████████████████████████          | 1035/1326 [05:04<01:25,  3.40it/s]

 78%|███████████████████████████████████▏         | 1036/1326 [05:04<01:25,  3.40it/s]

 78%|███████████████████████████████████▏         | 1037/1326 [05:05<01:24,  3.40it/s]

 78%|███████████████████████████████████▏         | 1038/1326 [05:05<01:24,  3.40it/s]

 78%|███████████████████████████████████▎         | 1039/1326 [05:05<01:24,  3.40it/s]

 78%|███████████████████████████████████▎         | 1040/1326 [05:06<01:24,  3.40it/s]

 79%|███████████████████████████████████▎         | 1041/1326 [05:06<01:23,  3.41it/s]

 79%|███████████████████████████████████▎         | 1042/1326 [05:06<01:23,  3.41it/s]

 79%|███████████████████████████████████▍         | 1043/1326 [05:06<01:23,  3.41it/s]

 79%|███████████████████████████████████▍         | 1044/1326 [05:07<01:22,  3.40it/s]

 79%|███████████████████████████████████▍         | 1045/1326 [05:07<01:22,  3.40it/s]

 79%|███████████████████████████████████▍         | 1046/1326 [05:07<01:22,  3.40it/s]

 79%|███████████████████████████████████▌         | 1047/1326 [05:08<01:21,  3.40it/s]

 79%|███████████████████████████████████▌         | 1048/1326 [05:08<01:21,  3.40it/s]

 79%|███████████████████████████████████▌         | 1049/1326 [05:08<01:21,  3.40it/s]

 79%|███████████████████████████████████▋         | 1050/1326 [05:09<01:21,  3.41it/s]

 79%|███████████████████████████████████▋         | 1051/1326 [05:09<01:20,  3.40it/s]

 79%|███████████████████████████████████▋         | 1052/1326 [05:09<01:20,  3.40it/s]

 79%|███████████████████████████████████▋         | 1053/1326 [05:09<01:20,  3.40it/s]

 79%|███████████████████████████████████▊         | 1054/1326 [05:10<01:19,  3.40it/s]

 80%|███████████████████████████████████▊         | 1055/1326 [05:10<01:19,  3.40it/s]

 80%|███████████████████████████████████▊         | 1056/1326 [05:10<01:19,  3.40it/s]

 80%|███████████████████████████████████▊         | 1057/1326 [05:11<01:19,  3.40it/s]

 80%|███████████████████████████████████▉         | 1058/1326 [05:11<01:18,  3.40it/s]

 80%|███████████████████████████████████▉         | 1059/1326 [05:11<01:18,  3.40it/s]

 80%|███████████████████████████████████▉         | 1060/1326 [05:11<01:18,  3.40it/s]

 80%|████████████████████████████████████         | 1061/1326 [05:12<01:17,  3.40it/s]

 80%|████████████████████████████████████         | 1062/1326 [05:12<01:17,  3.40it/s]

 80%|████████████████████████████████████         | 1063/1326 [05:12<01:17,  3.40it/s]

 80%|████████████████████████████████████         | 1064/1326 [05:13<01:16,  3.40it/s]

 80%|████████████████████████████████████▏        | 1065/1326 [05:13<01:16,  3.40it/s]

 80%|████████████████████████████████████▏        | 1066/1326 [05:13<01:16,  3.40it/s]

 80%|████████████████████████████████████▏        | 1067/1326 [05:14<01:16,  3.40it/s]

 81%|████████████████████████████████████▏        | 1068/1326 [05:14<01:15,  3.40it/s]

 81%|████████████████████████████████████▎        | 1069/1326 [05:14<01:15,  3.40it/s]

 81%|████████████████████████████████████▎        | 1070/1326 [05:14<01:15,  3.40it/s]

 81%|████████████████████████████████████▎        | 1071/1326 [05:15<01:14,  3.40it/s]

 81%|████████████████████████████████████▍        | 1072/1326 [05:15<01:14,  3.40it/s]

 81%|████████████████████████████████████▍        | 1073/1326 [05:15<01:14,  3.40it/s]

 81%|████████████████████████████████████▍        | 1074/1326 [05:16<01:14,  3.40it/s]

 81%|████████████████████████████████████▍        | 1075/1326 [05:16<01:13,  3.40it/s]

 81%|████████████████████████████████████▌        | 1076/1326 [05:16<01:13,  3.40it/s]

 81%|████████████████████████████████████▌        | 1077/1326 [05:16<01:13,  3.40it/s]

 81%|████████████████████████████████████▌        | 1078/1326 [05:17<01:12,  3.40it/s]

 81%|████████████████████████████████████▌        | 1079/1326 [05:17<01:12,  3.40it/s]

 81%|████████████████████████████████████▋        | 1080/1326 [05:17<01:12,  3.40it/s]

 82%|████████████████████████████████████▋        | 1081/1326 [05:18<01:11,  3.40it/s]

 82%|████████████████████████████████████▋        | 1082/1326 [05:18<01:11,  3.40it/s]

 82%|████████████████████████████████████▊        | 1083/1326 [05:18<01:11,  3.40it/s]

 82%|████████████████████████████████████▊        | 1084/1326 [05:19<01:11,  3.40it/s]

 82%|████████████████████████████████████▊        | 1085/1326 [05:19<01:10,  3.40it/s]

 82%|████████████████████████████████████▊        | 1086/1326 [05:19<01:10,  3.40it/s]

 82%|████████████████████████████████████▉        | 1087/1326 [05:19<01:10,  3.40it/s]

 82%|████████████████████████████████████▉        | 1088/1326 [05:20<01:09,  3.40it/s]

 82%|████████████████████████████████████▉        | 1089/1326 [05:20<01:09,  3.40it/s]

 82%|████████████████████████████████████▉        | 1090/1326 [05:20<01:09,  3.40it/s]

 82%|█████████████████████████████████████        | 1091/1326 [05:21<01:09,  3.40it/s]

 82%|█████████████████████████████████████        | 1092/1326 [05:21<01:08,  3.40it/s]

 82%|█████████████████████████████████████        | 1093/1326 [05:21<01:08,  3.40it/s]

 83%|█████████████████████████████████████▏       | 1094/1326 [05:21<01:08,  3.40it/s]

 83%|█████████████████████████████████████▏       | 1095/1326 [05:22<01:07,  3.40it/s]

 83%|█████████████████████████████████████▏       | 1096/1326 [05:22<01:07,  3.40it/s]

 83%|█████████████████████████████████████▏       | 1097/1326 [05:22<01:07,  3.40it/s]

 83%|█████████████████████████████████████▎       | 1098/1326 [05:23<01:07,  3.40it/s]

 83%|█████████████████████████████████████▎       | 1099/1326 [05:23<01:06,  3.40it/s]

 83%|█████████████████████████████████████▎       | 1100/1326 [05:23<01:06,  3.40it/s]

 83%|█████████████████████████████████████▎       | 1101/1326 [05:24<01:06,  3.40it/s]

 83%|█████████████████████████████████████▍       | 1102/1326 [05:24<01:05,  3.40it/s]

 83%|█████████████████████████████████████▍       | 1103/1326 [05:24<01:05,  3.40it/s]

 83%|█████████████████████████████████████▍       | 1104/1326 [05:24<01:05,  3.40it/s]

 83%|█████████████████████████████████████▌       | 1105/1326 [05:25<01:04,  3.41it/s]

 83%|█████████████████████████████████████▌       | 1106/1326 [05:25<01:04,  3.40it/s]

 83%|█████████████████████████████████████▌       | 1107/1326 [05:25<01:04,  3.40it/s]

 84%|█████████████████████████████████████▌       | 1108/1326 [05:26<01:04,  3.40it/s]

 84%|█████████████████████████████████████▋       | 1109/1326 [05:26<01:03,  3.40it/s]

 84%|█████████████████████████████████████▋       | 1110/1326 [05:26<01:03,  3.40it/s]

 84%|█████████████████████████████████████▋       | 1111/1326 [05:26<01:03,  3.40it/s]

 84%|█████████████████████████████████████▋       | 1112/1326 [05:27<01:02,  3.40it/s]

 84%|█████████████████████████████████████▊       | 1113/1326 [05:27<01:02,  3.40it/s]

 84%|█████████████████████████████████████▊       | 1114/1326 [05:27<01:02,  3.40it/s]

 84%|█████████████████████████████████████▊       | 1115/1326 [05:28<01:01,  3.40it/s]

 84%|█████████████████████████████████████▊       | 1116/1326 [05:28<01:01,  3.40it/s]

 84%|█████████████████████████████████████▉       | 1117/1326 [05:28<01:01,  3.40it/s]

 84%|█████████████████████████████████████▉       | 1118/1326 [05:28<01:01,  3.40it/s]

 84%|█████████████████████████████████████▉       | 1119/1326 [05:29<01:00,  3.40it/s]

 84%|██████████████████████████████████████       | 1120/1326 [05:29<01:00,  3.40it/s]

 85%|██████████████████████████████████████       | 1121/1326 [05:29<01:00,  3.40it/s]

 85%|██████████████████████████████████████       | 1122/1326 [05:30<00:59,  3.40it/s]

 85%|██████████████████████████████████████       | 1123/1326 [05:30<00:59,  3.40it/s]

 85%|██████████████████████████████████████▏      | 1124/1326 [05:30<00:59,  3.40it/s]

 85%|██████████████████████████████████████▏      | 1125/1326 [05:31<00:59,  3.40it/s]

 85%|██████████████████████████████████████▏      | 1126/1326 [05:31<00:58,  3.40it/s]

 85%|██████████████████████████████████████▏      | 1127/1326 [05:31<00:58,  3.41it/s]

 85%|██████████████████████████████████████▎      | 1128/1326 [05:31<00:58,  3.41it/s]

 85%|██████████████████████████████████████▎      | 1129/1326 [05:32<00:57,  3.40it/s]

 85%|██████████████████████████████████████▎      | 1130/1326 [05:32<00:57,  3.41it/s]

 85%|██████████████████████████████████████▍      | 1131/1326 [05:32<00:57,  3.40it/s]

 85%|██████████████████████████████████████▍      | 1132/1326 [05:33<00:56,  3.40it/s]

 85%|██████████████████████████████████████▍      | 1133/1326 [05:33<00:56,  3.40it/s]

 86%|██████████████████████████████████████▍      | 1134/1326 [05:33<00:56,  3.40it/s]

 86%|██████████████████████████████████████▌      | 1135/1326 [05:33<00:56,  3.40it/s]

 86%|██████████████████████████████████████▌      | 1136/1326 [05:34<00:55,  3.40it/s]

 86%|██████████████████████████████████████▌      | 1137/1326 [05:34<00:55,  3.40it/s]

 86%|██████████████████████████████████████▌      | 1138/1326 [05:34<00:55,  3.40it/s]

 86%|██████████████████████████████████████▋      | 1139/1326 [05:35<00:54,  3.40it/s]

 86%|██████████████████████████████████████▋      | 1140/1326 [05:35<00:54,  3.40it/s]

 86%|██████████████████████████████████████▋      | 1141/1326 [05:35<00:54,  3.40it/s]

 86%|██████████████████████████████████████▊      | 1142/1326 [05:36<00:54,  3.40it/s]

 86%|██████████████████████████████████████▊      | 1143/1326 [05:36<00:53,  3.40it/s]

 86%|██████████████████████████████████████▊      | 1144/1326 [05:36<00:53,  3.40it/s]

 86%|██████████████████████████████████████▊      | 1145/1326 [05:36<00:53,  3.41it/s]

 86%|██████████████████████████████████████▉      | 1146/1326 [05:37<00:52,  3.41it/s]

 87%|██████████████████████████████████████▉      | 1147/1326 [05:37<00:52,  3.41it/s]

 87%|██████████████████████████████████████▉      | 1148/1326 [05:37<00:52,  3.40it/s]

 87%|██████████████████████████████████████▉      | 1149/1326 [05:38<00:51,  3.41it/s]

 87%|███████████████████████████████████████      | 1150/1326 [05:38<00:51,  3.41it/s]

 87%|███████████████████████████████████████      | 1151/1326 [05:38<00:51,  3.40it/s]

 87%|███████████████████████████████████████      | 1152/1326 [05:38<00:51,  3.40it/s]

 87%|███████████████████████████████████████▏     | 1153/1326 [05:39<00:50,  3.40it/s]

 87%|███████████████████████████████████████▏     | 1154/1326 [05:39<00:50,  3.41it/s]

 87%|███████████████████████████████████████▏     | 1155/1326 [05:39<00:50,  3.40it/s]

 87%|███████████████████████████████████████▏     | 1156/1326 [05:40<00:49,  3.41it/s]

 87%|███████████████████████████████████████▎     | 1157/1326 [05:40<00:49,  3.41it/s]

 87%|███████████████████████████████████████▎     | 1158/1326 [05:40<00:49,  3.40it/s]

 87%|███████████████████████████████████████▎     | 1159/1326 [05:41<00:49,  3.41it/s]

 87%|███████████████████████████████████████▎     | 1160/1326 [05:41<00:48,  3.41it/s]

 88%|███████████████████████████████████████▍     | 1161/1326 [05:41<00:48,  3.40it/s]

 88%|███████████████████████████████████████▍     | 1162/1326 [05:41<00:48,  3.40it/s]

 88%|███████████████████████████████████████▍     | 1163/1326 [05:42<00:47,  3.40it/s]

 88%|███████████████████████████████████████▌     | 1164/1326 [05:42<00:47,  3.40it/s]

 88%|███████████████████████████████████████▌     | 1165/1326 [05:42<00:47,  3.40it/s]

 88%|███████████████████████████████████████▌     | 1166/1326 [05:43<00:46,  3.40it/s]

 88%|███████████████████████████████████████▌     | 1167/1326 [05:43<00:46,  3.41it/s]

 88%|███████████████████████████████████████▋     | 1168/1326 [05:43<00:46,  3.40it/s]

 88%|███████████████████████████████████████▋     | 1169/1326 [05:43<00:46,  3.41it/s]

 88%|███████████████████████████████████████▋     | 1170/1326 [05:44<00:45,  3.41it/s]

 88%|███████████████████████████████████████▋     | 1171/1326 [05:44<00:45,  3.41it/s]

 88%|███████████████████████████████████████▊     | 1172/1326 [05:44<00:45,  3.41it/s]

 88%|███████████████████████████████████████▊     | 1173/1326 [05:45<00:44,  3.40it/s]

 89%|███████████████████████████████████████▊     | 1174/1326 [05:45<00:44,  3.40it/s]

 89%|███████████████████████████████████████▉     | 1175/1326 [05:45<00:44,  3.40it/s]

 89%|███████████████████████████████████████▉     | 1176/1326 [05:46<00:44,  3.41it/s]

 89%|███████████████████████████████████████▉     | 1177/1326 [05:46<00:43,  3.40it/s]

 89%|███████████████████████████████████████▉     | 1178/1326 [05:46<00:43,  3.40it/s]

 89%|████████████████████████████████████████     | 1179/1326 [05:46<00:43,  3.40it/s]

 89%|████████████████████████████████████████     | 1180/1326 [05:47<00:42,  3.40it/s]

 89%|████████████████████████████████████████     | 1181/1326 [05:47<00:42,  3.40it/s]

 89%|████████████████████████████████████████     | 1182/1326 [05:47<00:42,  3.40it/s]

 89%|████████████████████████████████████████▏    | 1183/1326 [05:48<00:42,  3.40it/s]

 89%|████████████████████████████████████████▏    | 1184/1326 [05:48<00:41,  3.40it/s]

 89%|████████████████████████████████████████▏    | 1185/1326 [05:48<00:41,  3.40it/s]

 89%|████████████████████████████████████████▏    | 1186/1326 [05:48<00:41,  3.40it/s]

 90%|████████████████████████████████████████▎    | 1187/1326 [05:49<00:40,  3.40it/s]

 90%|████████████████████████████████████████▎    | 1188/1326 [05:49<00:40,  3.40it/s]

 90%|████████████████████████████████████████▎    | 1189/1326 [05:49<00:40,  3.40it/s]

 90%|████████████████████████████████████████▍    | 1190/1326 [05:50<00:39,  3.41it/s]

 90%|████████████████████████████████████████▍    | 1191/1326 [05:50<00:39,  3.41it/s]

 90%|████████████████████████████████████████▍    | 1192/1326 [05:50<00:39,  3.41it/s]

 90%|████████████████████████████████████████▍    | 1193/1326 [05:51<00:39,  3.41it/s]

 90%|████████████████████████████████████████▌    | 1194/1326 [05:51<00:38,  3.41it/s]

 90%|████████████████████████████████████████▌    | 1195/1326 [05:51<00:38,  3.41it/s]

 90%|████████████████████████████████████████▌    | 1196/1326 [05:51<00:38,  3.40it/s]

 90%|████████████████████████████████████████▌    | 1197/1326 [05:52<00:37,  3.40it/s]

 90%|████████████████████████████████████████▋    | 1198/1326 [05:52<00:37,  3.41it/s]

 90%|████████████████████████████████████████▋    | 1199/1326 [05:52<00:37,  3.41it/s]

 90%|████████████████████████████████████████▋    | 1200/1326 [05:53<00:37,  3.40it/s]

 91%|████████████████████████████████████████▊    | 1201/1326 [05:53<00:36,  3.41it/s]

 91%|████████████████████████████████████████▊    | 1202/1326 [05:53<00:36,  3.40it/s]

 91%|████████████████████████████████████████▊    | 1203/1326 [05:53<00:36,  3.40it/s]

 91%|████████████████████████████████████████▊    | 1204/1326 [05:54<00:35,  3.40it/s]

 91%|████████████████████████████████████████▉    | 1205/1326 [05:54<00:35,  3.40it/s]

 91%|████████████████████████████████████████▉    | 1206/1326 [05:54<00:35,  3.40it/s]

 91%|████████████████████████████████████████▉    | 1207/1326 [05:55<00:34,  3.40it/s]

 91%|████████████████████████████████████████▉    | 1208/1326 [05:55<00:34,  3.40it/s]

 91%|█████████████████████████████████████████    | 1209/1326 [05:55<00:34,  3.40it/s]

 91%|█████████████████████████████████████████    | 1210/1326 [05:56<00:34,  3.40it/s]

 91%|█████████████████████████████████████████    | 1211/1326 [05:56<00:33,  3.40it/s]

 91%|█████████████████████████████████████████▏   | 1212/1326 [05:56<00:33,  3.40it/s]

 91%|█████████████████████████████████████████▏   | 1213/1326 [05:56<00:33,  3.40it/s]

 92%|█████████████████████████████████████████▏   | 1214/1326 [05:57<00:32,  3.41it/s]

 92%|█████████████████████████████████████████▏   | 1215/1326 [05:57<00:32,  3.40it/s]

 92%|█████████████████████████████████████████▎   | 1216/1326 [05:57<00:32,  3.40it/s]

 92%|█████████████████████████████████████████▎   | 1217/1326 [05:58<00:32,  3.40it/s]

 92%|█████████████████████████████████████████▎   | 1218/1326 [05:58<00:31,  3.40it/s]

 92%|█████████████████████████████████████████▎   | 1219/1326 [05:58<00:31,  3.40it/s]

 92%|█████████████████████████████████████████▍   | 1220/1326 [05:58<00:31,  3.40it/s]

 92%|█████████████████████████████████████████▍   | 1221/1326 [05:59<00:30,  3.40it/s]

 92%|█████████████████████████████████████████▍   | 1222/1326 [05:59<00:30,  3.40it/s]

 92%|█████████████████████████████████████████▌   | 1223/1326 [05:59<00:30,  3.40it/s]

 92%|█████████████████████████████████████████▌   | 1224/1326 [06:00<00:29,  3.40it/s]

 92%|█████████████████████████████████████████▌   | 1225/1326 [06:00<00:29,  3.40it/s]

 92%|█████████████████████████████████████████▌   | 1226/1326 [06:00<00:29,  3.40it/s]

 93%|█████████████████████████████████████████▋   | 1227/1326 [06:01<00:29,  3.40it/s]

 93%|█████████████████████████████████████████▋   | 1228/1326 [06:01<00:28,  3.40it/s]

 93%|█████████████████████████████████████████▋   | 1229/1326 [06:01<00:28,  3.40it/s]

 93%|█████████████████████████████████████████▋   | 1230/1326 [06:01<00:28,  3.41it/s]

 93%|█████████████████████████████████████████▊   | 1231/1326 [06:02<00:27,  3.41it/s]

 93%|█████████████████████████████████████████▊   | 1232/1326 [06:02<00:27,  3.41it/s]

 93%|█████████████████████████████████████████▊   | 1233/1326 [06:02<00:27,  3.41it/s]

 93%|█████████████████████████████████████████▉   | 1234/1326 [06:03<00:27,  3.41it/s]

 93%|█████████████████████████████████████████▉   | 1235/1326 [06:03<00:26,  3.41it/s]

 93%|█████████████████████████████████████████▉   | 1236/1326 [06:03<00:26,  3.40it/s]

 93%|█████████████████████████████████████████▉   | 1237/1326 [06:03<00:26,  3.41it/s]

 93%|██████████████████████████████████████████   | 1238/1326 [06:04<00:25,  3.41it/s]

 93%|██████████████████████████████████████████   | 1239/1326 [06:04<00:25,  3.41it/s]

 94%|██████████████████████████████████████████   | 1240/1326 [06:04<00:25,  3.41it/s]

 94%|██████████████████████████████████████████   | 1241/1326 [06:05<00:24,  3.41it/s]

 94%|██████████████████████████████████████████▏  | 1242/1326 [06:05<00:24,  3.41it/s]

 94%|██████████████████████████████████████████▏  | 1243/1326 [06:05<00:24,  3.41it/s]

 94%|██████████████████████████████████████████▏  | 1244/1326 [06:06<00:24,  3.41it/s]

 94%|██████████████████████████████████████████▎  | 1245/1326 [06:06<00:23,  3.40it/s]

 94%|██████████████████████████████████████████▎  | 1246/1326 [06:06<00:23,  3.40it/s]

 94%|██████████████████████████████████████████▎  | 1247/1326 [06:06<00:23,  3.41it/s]

 94%|██████████████████████████████████████████▎  | 1248/1326 [06:07<00:22,  3.41it/s]

 94%|██████████████████████████████████████████▍  | 1249/1326 [06:07<00:22,  3.40it/s]

 94%|██████████████████████████████████████████▍  | 1250/1326 [06:07<00:22,  3.40it/s]

 94%|██████████████████████████████████████████▍  | 1251/1326 [06:08<00:22,  3.40it/s]

 94%|██████████████████████████████████████████▍  | 1252/1326 [06:08<00:21,  3.41it/s]

 94%|██████████████████████████████████████████▌  | 1253/1326 [06:08<00:21,  3.41it/s]

 95%|██████████████████████████████████████████▌  | 1254/1326 [06:08<00:21,  3.41it/s]

 95%|██████████████████████████████████████████▌  | 1255/1326 [06:09<00:20,  3.41it/s]

 95%|██████████████████████████████████████████▌  | 1256/1326 [06:09<00:20,  3.41it/s]

 95%|██████████████████████████████████████████▋  | 1257/1326 [06:09<00:20,  3.41it/s]

 95%|██████████████████████████████████████████▋  | 1258/1326 [06:10<00:19,  3.40it/s]

 95%|██████████████████████████████████████████▋  | 1259/1326 [06:10<00:19,  3.40it/s]

 95%|██████████████████████████████████████████▊  | 1260/1326 [06:10<00:19,  3.40it/s]

 95%|██████████████████████████████████████████▊  | 1261/1326 [06:10<00:19,  3.41it/s]

 95%|██████████████████████████████████████████▊  | 1262/1326 [06:11<00:18,  3.41it/s]

 95%|██████████████████████████████████████████▊  | 1263/1326 [06:11<00:18,  3.41it/s]

 95%|██████████████████████████████████████████▉  | 1264/1326 [06:11<00:18,  3.41it/s]

 95%|██████████████████████████████████████████▉  | 1265/1326 [06:12<00:17,  3.40it/s]

 95%|██████████████████████████████████████████▉  | 1266/1326 [06:12<00:17,  3.41it/s]

 96%|██████████████████████████████████████████▉  | 1267/1326 [06:12<00:17,  3.41it/s]

 96%|███████████████████████████████████████████  | 1268/1326 [06:13<00:17,  3.41it/s]

 96%|███████████████████████████████████████████  | 1269/1326 [06:13<00:16,  3.41it/s]

 96%|███████████████████████████████████████████  | 1270/1326 [06:13<00:16,  3.41it/s]

 96%|███████████████████████████████████████████▏ | 1271/1326 [06:13<00:16,  3.41it/s]

 96%|███████████████████████████████████████████▏ | 1272/1326 [06:14<00:15,  3.41it/s]

 96%|███████████████████████████████████████████▏ | 1273/1326 [06:14<00:15,  3.41it/s]

 96%|███████████████████████████████████████████▏ | 1274/1326 [06:14<00:15,  3.41it/s]

 96%|███████████████████████████████████████████▎ | 1275/1326 [06:15<00:14,  3.41it/s]

 96%|███████████████████████████████████████████▎ | 1276/1326 [06:15<00:14,  3.41it/s]

 96%|███████████████████████████████████████████▎ | 1277/1326 [06:15<00:14,  3.41it/s]

 96%|███████████████████████████████████████████▎ | 1278/1326 [06:15<00:14,  3.41it/s]

 96%|███████████████████████████████████████████▍ | 1279/1326 [06:16<00:13,  3.41it/s]

 97%|███████████████████████████████████████████▍ | 1280/1326 [06:16<00:13,  3.41it/s]

 97%|███████████████████████████████████████████▍ | 1281/1326 [06:16<00:13,  3.41it/s]

 97%|███████████████████████████████████████████▌ | 1282/1326 [06:17<00:12,  3.41it/s]

 97%|███████████████████████████████████████████▌ | 1283/1326 [06:17<00:12,  3.40it/s]

 97%|███████████████████████████████████████████▌ | 1284/1326 [06:17<00:12,  3.40it/s]

 97%|███████████████████████████████████████████▌ | 1285/1326 [06:18<00:12,  3.40it/s]

 97%|███████████████████████████████████████████▋ | 1286/1326 [06:18<00:11,  3.40it/s]

 97%|███████████████████████████████████████████▋ | 1287/1326 [06:18<00:11,  3.40it/s]

 97%|███████████████████████████████████████████▋ | 1288/1326 [06:18<00:11,  3.40it/s]

 97%|███████████████████████████████████████████▋ | 1289/1326 [06:19<00:10,  3.40it/s]

 97%|███████████████████████████████████████████▊ | 1290/1326 [06:19<00:10,  3.40it/s]

 97%|███████████████████████████████████████████▊ | 1291/1326 [06:19<00:10,  3.41it/s]

 97%|███████████████████████████████████████████▊ | 1292/1326 [06:20<00:09,  3.41it/s]

 98%|███████████████████████████████████████████▉ | 1293/1326 [06:20<00:09,  3.41it/s]

 98%|███████████████████████████████████████████▉ | 1294/1326 [06:20<00:09,  3.41it/s]

 98%|███████████████████████████████████████████▉ | 1295/1326 [06:20<00:09,  3.41it/s]

 98%|███████████████████████████████████████████▉ | 1296/1326 [06:21<00:08,  3.40it/s]

 98%|████████████████████████████████████████████ | 1297/1326 [06:21<00:08,  3.40it/s]

 98%|████████████████████████████████████████████ | 1298/1326 [06:21<00:08,  3.40it/s]

 98%|████████████████████████████████████████████ | 1299/1326 [06:22<00:07,  3.40it/s]

 98%|████████████████████████████████████████████ | 1300/1326 [06:22<00:07,  3.40it/s]

 98%|████████████████████████████████████████████▏| 1301/1326 [06:22<00:07,  3.40it/s]

 98%|████████████████████████████████████████████▏| 1302/1326 [06:23<00:07,  3.40it/s]

 98%|████████████████████████████████████████████▏| 1303/1326 [06:23<00:06,  3.40it/s]

 98%|████████████████████████████████████████████▎| 1304/1326 [06:23<00:06,  3.40it/s]

 98%|████████████████████████████████████████████▎| 1305/1326 [06:23<00:06,  3.40it/s]

 98%|████████████████████████████████████████████▎| 1306/1326 [06:24<00:05,  3.40it/s]

 99%|████████████████████████████████████████████▎| 1307/1326 [06:24<00:05,  3.40it/s]

 99%|████████████████████████████████████████████▍| 1308/1326 [06:24<00:05,  3.40it/s]

 99%|████████████████████████████████████████████▍| 1309/1326 [06:25<00:04,  3.40it/s]

 99%|████████████████████████████████████████████▍| 1310/1326 [06:25<00:04,  3.40it/s]

 99%|████████████████████████████████████████████▍| 1311/1326 [06:25<00:04,  3.40it/s]

 99%|████████████████████████████████████████████▌| 1312/1326 [06:25<00:04,  3.40it/s]

 99%|████████████████████████████████████████████▌| 1313/1326 [06:26<00:03,  3.40it/s]

 99%|████████████████████████████████████████████▌| 1314/1326 [06:26<00:03,  3.41it/s]

 99%|████████████████████████████████████████████▋| 1315/1326 [06:26<00:03,  3.41it/s]

 99%|████████████████████████████████████████████▋| 1316/1326 [06:27<00:02,  3.40it/s]

 99%|████████████████████████████████████████████▋| 1317/1326 [06:27<00:02,  3.41it/s]

 99%|████████████████████████████████████████████▋| 1318/1326 [06:27<00:02,  3.41it/s]

 99%|████████████████████████████████████████████▊| 1319/1326 [06:28<00:02,  3.41it/s]

100%|████████████████████████████████████████████▊| 1320/1326 [06:28<00:01,  3.41it/s]

100%|████████████████████████████████████████████▊| 1321/1326 [06:28<00:01,  3.40it/s]

100%|████████████████████████████████████████████▊| 1322/1326 [06:28<00:01,  3.40it/s]

100%|████████████████████████████████████████████▉| 1323/1326 [06:29<00:00,  3.40it/s]

100%|████████████████████████████████████████████▉| 1324/1326 [06:29<00:00,  3.40it/s]

100%|████████████████████████████████████████████▉| 1325/1326 [06:29<00:00,  3.40it/s]

100%|█████████████████████████████████████████████| 1326/1326 [06:30<00:00,  3.40it/s]

100%|█████████████████████████████████████████████| 1326/1326 [06:30<00:00,  3.40it/s]

Scoring likelihoods of 3893 variant sequences with Evo 2...

  0%|                                                        | 0/3893 [00:00<?, ?it/s]

  0%|                                                | 1/3893 [00:00<19:01,  3.41it/s]

  0%|                                                | 2/3893 [00:00<19:02,  3.41it/s]

  0%|                                                | 3/3893 [00:00<19:02,  3.41it/s]

  0%|                                                | 4/3893 [00:01<19:02,  3.40it/s]

  0%|                                                | 5/3893 [00:01<19:01,  3.41it/s]

  0%|                                                | 6/3893 [00:01<19:01,  3.41it/s]

  0%|                                                | 7/3893 [00:02<19:01,  3.41it/s]

  0%|                                                | 8/3893 [00:02<19:01,  3.40it/s]

  0%|                                                | 9/3893 [00:02<19:00,  3.40it/s]

  0%|                                               | 10/3893 [00:02<19:00,  3.40it/s]

  0%|▏                                              | 11/3893 [00:03<19:00,  3.40it/s]

  0%|▏                                              | 12/3893 [00:03<18:59,  3.41it/s]

  0%|▏                                              | 13/3893 [00:03<18:59,  3.40it/s]

  0%|▏                                              | 14/3893 [00:04<18:59,  3.40it/s]

  0%|▏                                              | 15/3893 [00:04<18:58,  3.41it/s]

  0%|▏                                              | 16/3893 [00:04<18:58,  3.40it/s]

  0%|▏                                              | 17/3893 [00:04<18:58,  3.41it/s]

  0%|▏                                              | 18/3893 [00:05<18:57,  3.41it/s]

  0%|▏                                              | 19/3893 [00:05<18:57,  3.40it/s]

  1%|▏                                              | 20/3893 [00:05<18:57,  3.40it/s]

  1%|▎                                              | 21/3893 [00:06<18:57,  3.40it/s]

  1%|▎                                              | 22/3893 [00:06<18:56,  3.40it/s]

  1%|▎                                              | 23/3893 [00:06<18:56,  3.41it/s]

  1%|▎                                              | 24/3893 [00:07<18:55,  3.41it/s]

  1%|▎                                              | 25/3893 [00:07<18:55,  3.41it/s]

  1%|▎                                              | 26/3893 [00:07<18:55,  3.41it/s]

  1%|▎                                              | 27/3893 [00:07<18:54,  3.41it/s]

  1%|▎                                              | 28/3893 [00:08<18:54,  3.41it/s]

  1%|▎                                              | 29/3893 [00:08<18:54,  3.41it/s]

  1%|▎                                              | 30/3893 [00:08<18:54,  3.41it/s]

  1%|▎                                              | 31/3893 [00:09<18:53,  3.41it/s]

  1%|▍                                              | 32/3893 [00:09<18:53,  3.41it/s]

  1%|▍                                              | 33/3893 [00:09<18:53,  3.41it/s]

  1%|▍                                              | 34/3893 [00:09<18:53,  3.41it/s]

  1%|▍                                              | 35/3893 [00:10<18:52,  3.41it/s]

  1%|▍                                              | 36/3893 [00:10<18:52,  3.41it/s]

  1%|▍                                              | 37/3893 [00:10<18:52,  3.41it/s]

  1%|▍                                              | 38/3893 [00:11<18:52,  3.40it/s]

  1%|▍                                              | 39/3893 [00:11<18:51,  3.40it/s]

  1%|▍                                              | 40/3893 [00:11<18:51,  3.41it/s]

  1%|▍                                              | 41/3893 [00:12<18:51,  3.40it/s]

  1%|▌                                              | 42/3893 [00:12<18:51,  3.40it/s]

  1%|▌                                              | 43/3893 [00:12<18:50,  3.40it/s]

  1%|▌                                              | 44/3893 [00:12<18:50,  3.40it/s]

  1%|▌                                              | 45/3893 [00:13<18:50,  3.40it/s]

  1%|▌                                              | 46/3893 [00:13<18:50,  3.40it/s]

  1%|▌                                              | 47/3893 [00:13<18:50,  3.40it/s]

  1%|▌                                              | 48/3893 [00:14<18:49,  3.40it/s]

  1%|▌                                              | 49/3893 [00:14<18:49,  3.40it/s]

  1%|▌                                              | 50/3893 [00:14<18:48,  3.41it/s]

  1%|▌                                              | 51/3893 [00:14<18:48,  3.41it/s]

  1%|▋                                              | 52/3893 [00:15<18:48,  3.40it/s]

  1%|▋                                              | 53/3893 [00:15<18:47,  3.41it/s]

  1%|▋                                              | 54/3893 [00:15<18:47,  3.40it/s]

  1%|▋                                              | 55/3893 [00:16<18:47,  3.40it/s]

  1%|▋                                              | 56/3893 [00:16<18:46,  3.40it/s]

  1%|▋                                              | 57/3893 [00:16<18:46,  3.41it/s]

  1%|▋                                              | 58/3893 [00:17<18:46,  3.41it/s]

  2%|▋                                              | 59/3893 [00:17<18:45,  3.41it/s]

  2%|▋                                              | 60/3893 [00:17<18:45,  3.41it/s]

  2%|▋                                              | 61/3893 [00:17<18:45,  3.41it/s]

  2%|▋                                              | 62/3893 [00:18<18:44,  3.41it/s]

  2%|▊                                              | 63/3893 [00:18<18:44,  3.41it/s]

  2%|▊                                              | 64/3893 [00:18<18:44,  3.41it/s]

  2%|▊                                              | 65/3893 [00:19<18:44,  3.41it/s]

  2%|▊                                              | 66/3893 [00:19<18:43,  3.41it/s]

  2%|▊                                              | 67/3893 [00:19<18:43,  3.41it/s]

  2%|▊                                              | 68/3893 [00:19<18:43,  3.41it/s]

  2%|▊                                              | 69/3893 [00:20<18:42,  3.41it/s]

  2%|▊                                              | 70/3893 [00:20<18:42,  3.40it/s]

  2%|▊                                              | 71/3893 [00:20<18:42,  3.41it/s]

  2%|▊                                              | 72/3893 [00:21<18:41,  3.41it/s]

  2%|▉                                              | 73/3893 [00:21<18:41,  3.41it/s]

  2%|▉                                              | 74/3893 [00:21<18:41,  3.41it/s]

  2%|▉                                              | 75/3893 [00:22<18:40,  3.41it/s]

  2%|▉                                              | 76/3893 [00:22<18:40,  3.41it/s]

  2%|▉                                              | 77/3893 [00:22<18:40,  3.41it/s]

  2%|▉                                              | 78/3893 [00:22<18:40,  3.40it/s]

  2%|▉                                              | 79/3893 [00:23<18:40,  3.40it/s]

  2%|▉                                              | 80/3893 [00:23<18:40,  3.40it/s]

  2%|▉                                              | 81/3893 [00:23<18:40,  3.40it/s]

  2%|▉                                              | 82/3893 [00:24<18:39,  3.40it/s]

  2%|█                                              | 83/3893 [00:24<18:39,  3.40it/s]

  2%|█                                              | 84/3893 [00:24<18:39,  3.40it/s]

  2%|█                                              | 85/3893 [00:24<18:38,  3.40it/s]

  2%|█                                              | 86/3893 [00:25<18:38,  3.40it/s]

  2%|█                                              | 87/3893 [00:25<18:38,  3.40it/s]

  2%|█                                              | 88/3893 [00:25<18:37,  3.40it/s]

  2%|█                                              | 89/3893 [00:26<18:37,  3.40it/s]

  2%|█                                              | 90/3893 [00:26<18:37,  3.40it/s]

  2%|█                                              | 91/3893 [00:26<18:37,  3.40it/s]

  2%|█                                              | 92/3893 [00:27<18:36,  3.40it/s]

  2%|█                                              | 93/3893 [00:27<18:36,  3.40it/s]

  2%|█▏                                             | 94/3893 [00:27<18:36,  3.40it/s]

  2%|█▏                                             | 95/3893 [00:27<18:35,  3.40it/s]

  2%|█▏                                             | 96/3893 [00:28<18:35,  3.41it/s]

  2%|█▏                                             | 97/3893 [00:28<18:34,  3.40it/s]

  3%|█▏                                             | 98/3893 [00:28<18:34,  3.41it/s]

  3%|█▏                                             | 99/3893 [00:29<18:34,  3.40it/s]

  3%|█▏                                            | 100/3893 [00:29<18:34,  3.40it/s]

  3%|█▏                                            | 101/3893 [00:29<18:33,  3.40it/s]

  3%|█▏                                            | 102/3893 [00:29<18:33,  3.40it/s]

  3%|█▏                                            | 103/3893 [00:30<18:32,  3.41it/s]

  3%|█▏                                            | 104/3893 [00:30<18:32,  3.41it/s]

  3%|█▏                                            | 105/3893 [00:30<18:32,  3.41it/s]

  3%|█▎                                            | 106/3893 [00:31<18:32,  3.41it/s]

  3%|█▎                                            | 107/3893 [00:31<18:31,  3.41it/s]

  3%|█▎                                            | 108/3893 [00:31<18:31,  3.41it/s]

  3%|█▎                                            | 109/3893 [00:32<18:31,  3.41it/s]

  3%|█▎                                            | 110/3893 [00:32<18:30,  3.41it/s]

  3%|█▎                                            | 111/3893 [00:32<18:30,  3.41it/s]

  3%|█▎                                            | 112/3893 [00:32<18:29,  3.41it/s]

  3%|█▎                                            | 113/3893 [00:33<18:29,  3.41it/s]

  3%|█▎                                            | 114/3893 [00:33<18:29,  3.41it/s]

  3%|█▎                                            | 115/3893 [00:33<18:29,  3.40it/s]

  3%|█▎                                            | 116/3893 [00:34<18:29,  3.40it/s]

  3%|█▍                                            | 117/3893 [00:34<18:28,  3.40it/s]

  3%|█▍                                            | 118/3893 [00:34<18:28,  3.41it/s]

  3%|█▍                                            | 119/3893 [00:34<18:28,  3.41it/s]

  3%|█▍                                            | 120/3893 [00:35<18:27,  3.41it/s]

  3%|█▍                                            | 121/3893 [00:35<18:27,  3.41it/s]

  3%|█▍                                            | 122/3893 [00:35<18:27,  3.41it/s]

  3%|█▍                                            | 123/3893 [00:36<18:26,  3.41it/s]

  3%|█▍                                            | 124/3893 [00:36<18:26,  3.41it/s]

  3%|█▍                                            | 125/3893 [00:36<18:26,  3.41it/s]

  3%|█▍                                            | 126/3893 [00:37<18:25,  3.41it/s]

  3%|█▌                                            | 127/3893 [00:37<18:25,  3.41it/s]

  3%|█▌                                            | 128/3893 [00:37<18:25,  3.41it/s]

  3%|█▌                                            | 129/3893 [00:37<18:25,  3.41it/s]

  3%|█▌                                            | 130/3893 [00:38<18:24,  3.41it/s]

  3%|█▌                                            | 131/3893 [00:38<18:24,  3.41it/s]

  3%|█▌                                            | 132/3893 [00:38<18:23,  3.41it/s]

  3%|█▌                                            | 133/3893 [00:39<18:23,  3.41it/s]

  3%|█▌                                            | 134/3893 [00:39<18:23,  3.41it/s]

  3%|█▌                                            | 135/3893 [00:39<18:23,  3.41it/s]

  3%|█▌                                            | 136/3893 [00:39<18:22,  3.41it/s]

  4%|█▌                                            | 137/3893 [00:40<18:22,  3.41it/s]

  4%|█▋                                            | 138/3893 [00:40<18:22,  3.41it/s]

  4%|█▋                                            | 139/3893 [00:40<18:22,  3.41it/s]

  4%|█▋                                            | 140/3893 [00:41<18:21,  3.41it/s]

  4%|█▋                                            | 141/3893 [00:41<18:21,  3.41it/s]

  4%|█▋                                            | 142/3893 [00:41<18:21,  3.41it/s]

  4%|█▋                                            | 143/3893 [00:41<18:21,  3.41it/s]

  4%|█▋                                            | 144/3893 [00:42<18:20,  3.41it/s]

  4%|█▋                                            | 145/3893 [00:42<18:20,  3.41it/s]

  4%|█▋                                            | 146/3893 [00:42<18:20,  3.41it/s]

  4%|█▋                                            | 147/3893 [00:43<18:19,  3.41it/s]

  4%|█▋                                            | 148/3893 [00:43<18:19,  3.41it/s]

  4%|█▊                                            | 149/3893 [00:43<18:19,  3.41it/s]

  4%|█▊                                            | 150/3893 [00:44<18:18,  3.41it/s]

  4%|█▊                                            | 151/3893 [00:44<18:18,  3.41it/s]

  4%|█▊                                            | 152/3893 [00:44<18:18,  3.41it/s]

  4%|█▊                                            | 153/3893 [00:44<18:18,  3.40it/s]

  4%|█▊                                            | 154/3893 [00:45<18:18,  3.40it/s]

  4%|█▊                                            | 155/3893 [00:45<18:17,  3.40it/s]

  4%|█▊                                            | 156/3893 [00:45<18:17,  3.41it/s]

  4%|█▊                                            | 157/3893 [00:46<18:17,  3.41it/s]

  4%|█▊                                            | 158/3893 [00:46<18:16,  3.40it/s]

  4%|█▉                                            | 159/3893 [00:46<18:16,  3.41it/s]

  4%|█▉                                            | 160/3893 [00:46<18:16,  3.41it/s]

  4%|█▉                                            | 161/3893 [00:47<18:15,  3.41it/s]

  4%|█▉                                            | 162/3893 [00:47<18:15,  3.41it/s]

  4%|█▉                                            | 163/3893 [00:47<18:15,  3.41it/s]

  4%|█▉                                            | 164/3893 [00:48<18:14,  3.41it/s]

  4%|█▉                                            | 165/3893 [00:48<18:14,  3.41it/s]

  4%|█▉                                            | 166/3893 [00:48<18:14,  3.41it/s]

  4%|█▉                                            | 167/3893 [00:49<18:14,  3.40it/s]

  4%|█▉                                            | 168/3893 [00:49<18:14,  3.40it/s]

  4%|█▉                                            | 169/3893 [00:49<18:13,  3.40it/s]

  4%|██                                            | 170/3893 [00:49<18:13,  3.40it/s]

  4%|██                                            | 171/3893 [00:50<18:13,  3.40it/s]

  4%|██                                            | 172/3893 [00:50<18:13,  3.40it/s]

  4%|██                                            | 173/3893 [00:50<18:12,  3.40it/s]

  4%|██                                            | 174/3893 [00:51<18:12,  3.41it/s]

  4%|██                                            | 175/3893 [00:51<18:11,  3.41it/s]

  5%|██                                            | 176/3893 [00:51<18:11,  3.41it/s]

  5%|██                                            | 177/3893 [00:51<18:11,  3.41it/s]

  5%|██                                            | 178/3893 [00:52<18:10,  3.41it/s]

  5%|██                                            | 179/3893 [00:52<18:10,  3.41it/s]

  5%|██▏                                           | 180/3893 [00:52<18:10,  3.41it/s]

  5%|██▏                                           | 181/3893 [00:53<18:09,  3.41it/s]

  5%|██▏                                           | 182/3893 [00:53<18:09,  3.41it/s]

  5%|██▏                                           | 183/3893 [00:53<18:09,  3.41it/s]

  5%|██▏                                           | 184/3893 [00:54<18:09,  3.41it/s]

  5%|██▏                                           | 185/3893 [00:54<18:08,  3.41it/s]

  5%|██▏                                           | 186/3893 [00:54<18:08,  3.40it/s]

  5%|██▏                                           | 187/3893 [00:54<18:08,  3.41it/s]

  5%|██▏                                           | 188/3893 [00:55<18:07,  3.41it/s]

  5%|██▏                                           | 189/3893 [00:55<18:07,  3.41it/s]

  5%|██▏                                           | 190/3893 [00:55<18:07,  3.41it/s]

  5%|██▎                                           | 191/3893 [00:56<18:07,  3.41it/s]

  5%|██▎                                           | 192/3893 [00:56<18:07,  3.40it/s]

  5%|██▎                                           | 193/3893 [00:56<18:06,  3.40it/s]

  5%|██▎                                           | 194/3893 [00:56<18:06,  3.40it/s]

  5%|██▎                                           | 195/3893 [00:57<18:06,  3.40it/s]

  5%|██▎                                           | 196/3893 [00:57<18:05,  3.41it/s]

  5%|██▎                                           | 197/3893 [00:57<18:05,  3.41it/s]

  5%|██▎                                           | 198/3893 [00:58<18:04,  3.41it/s]

  5%|██▎                                           | 199/3893 [00:58<18:04,  3.41it/s]

  5%|██▎                                           | 200/3893 [00:58<18:04,  3.41it/s]

  5%|██▍                                           | 201/3893 [00:59<18:03,  3.41it/s]

  5%|██▍                                           | 202/3893 [00:59<18:03,  3.41it/s]

  5%|██▍                                           | 203/3893 [00:59<18:03,  3.41it/s]

  5%|██▍                                           | 204/3893 [00:59<18:03,  3.41it/s]

  5%|██▍                                           | 205/3893 [01:00<18:02,  3.41it/s]

  5%|██▍                                           | 206/3893 [01:00<18:02,  3.41it/s]

  5%|██▍                                           | 207/3893 [01:00<18:02,  3.41it/s]

  5%|██▍                                           | 208/3893 [01:01<18:01,  3.41it/s]

  5%|██▍                                           | 209/3893 [01:01<18:01,  3.41it/s]

  5%|██▍                                           | 210/3893 [01:01<18:01,  3.41it/s]

  5%|██▍                                           | 211/3893 [01:01<18:01,  3.41it/s]

  5%|██▌                                           | 212/3893 [01:02<18:01,  3.40it/s]

  5%|██▌                                           | 213/3893 [01:02<18:00,  3.41it/s]

  5%|██▌                                           | 214/3893 [01:02<18:00,  3.41it/s]

  6%|██▌                                           | 215/3893 [01:03<17:59,  3.41it/s]

  6%|██▌                                           | 216/3893 [01:03<17:59,  3.41it/s]

  6%|██▌                                           | 217/3893 [01:03<17:59,  3.41it/s]

  6%|██▌                                           | 218/3893 [01:04<17:59,  3.41it/s]

  6%|██▌                                           | 219/3893 [01:04<17:58,  3.41it/s]

  6%|██▌                                           | 220/3893 [01:04<17:58,  3.41it/s]

  6%|██▌                                           | 221/3893 [01:04<17:58,  3.41it/s]

  6%|██▌                                           | 222/3893 [01:05<17:58,  3.41it/s]

  6%|██▋                                           | 223/3893 [01:05<17:57,  3.41it/s]

  6%|██▋                                           | 224/3893 [01:05<17:57,  3.41it/s]

  6%|██▋                                           | 225/3893 [01:06<17:57,  3.40it/s]

  6%|██▋                                           | 226/3893 [01:06<17:56,  3.41it/s]

  6%|██▋                                           | 227/3893 [01:06<17:56,  3.41it/s]

  6%|██▋                                           | 228/3893 [01:06<17:56,  3.41it/s]

  6%|██▋                                           | 229/3893 [01:07<17:55,  3.41it/s]

  6%|██▋                                           | 230/3893 [01:07<17:55,  3.41it/s]

  6%|██▋                                           | 231/3893 [01:07<17:55,  3.41it/s]

  6%|██▋                                           | 232/3893 [01:08<17:55,  3.41it/s]

  6%|██▊                                           | 233/3893 [01:08<17:54,  3.40it/s]

  6%|██▊                                           | 234/3893 [01:08<17:54,  3.41it/s]

  6%|██▊                                           | 235/3893 [01:09<17:54,  3.40it/s]

  6%|██▊                                           | 236/3893 [01:09<17:54,  3.40it/s]

  6%|██▊                                           | 237/3893 [01:09<17:54,  3.40it/s]

  6%|██▊                                           | 238/3893 [01:09<17:53,  3.40it/s]

  6%|██▊                                           | 239/3893 [01:10<17:53,  3.40it/s]

  6%|██▊                                           | 240/3893 [01:10<17:53,  3.40it/s]

  6%|██▊                                           | 241/3893 [01:10<17:52,  3.40it/s]

  6%|██▊                                           | 242/3893 [01:11<17:52,  3.40it/s]

  6%|██▊                                           | 243/3893 [01:11<17:52,  3.40it/s]

  6%|██▉                                           | 244/3893 [01:11<17:52,  3.40it/s]

  6%|██▉                                           | 245/3893 [01:11<17:51,  3.40it/s]

  6%|██▉                                           | 246/3893 [01:12<17:51,  3.40it/s]

  6%|██▉                                           | 247/3893 [01:12<17:51,  3.40it/s]

  6%|██▉                                           | 248/3893 [01:12<17:50,  3.40it/s]

  6%|██▉                                           | 249/3893 [01:13<17:50,  3.40it/s]

  6%|██▉                                           | 250/3893 [01:13<17:50,  3.40it/s]

  6%|██▉                                           | 251/3893 [01:13<17:50,  3.40it/s]

  6%|██▉                                           | 252/3893 [01:14<17:49,  3.40it/s]

  6%|██▉                                           | 253/3893 [01:14<17:49,  3.40it/s]

  7%|███                                           | 254/3893 [01:14<17:49,  3.40it/s]

  7%|███                                           | 255/3893 [01:14<17:49,  3.40it/s]

  7%|███                                           | 256/3893 [01:15<17:48,  3.40it/s]

  7%|███                                           | 257/3893 [01:15<17:48,  3.40it/s]

  7%|███                                           | 258/3893 [01:15<17:48,  3.40it/s]

  7%|███                                           | 259/3893 [01:16<17:48,  3.40it/s]

  7%|███                                           | 260/3893 [01:16<17:47,  3.40it/s]

  7%|███                                           | 261/3893 [01:16<17:47,  3.40it/s]

  7%|███                                           | 262/3893 [01:16<17:46,  3.40it/s]

  7%|███                                           | 263/3893 [01:17<17:46,  3.40it/s]

  7%|███                                           | 264/3893 [01:17<17:46,  3.40it/s]

  7%|███▏                                          | 265/3893 [01:17<17:45,  3.41it/s]

  7%|███▏                                          | 266/3893 [01:18<17:45,  3.41it/s]

  7%|███▏                                          | 267/3893 [01:18<17:44,  3.40it/s]

  7%|███▏                                          | 268/3893 [01:18<17:44,  3.40it/s]

  7%|███▏                                          | 269/3893 [01:18<17:44,  3.41it/s]

  7%|███▏                                          | 270/3893 [01:19<17:43,  3.41it/s]

  7%|███▏                                          | 271/3893 [01:19<17:43,  3.41it/s]

  7%|███▏                                          | 272/3893 [01:19<17:43,  3.41it/s]

  7%|███▏                                          | 273/3893 [01:20<17:43,  3.40it/s]

  7%|███▏                                          | 274/3893 [01:20<17:43,  3.40it/s]

  7%|███▏                                          | 275/3893 [01:20<17:42,  3.41it/s]

  7%|███▎                                          | 276/3893 [01:21<17:42,  3.41it/s]

  7%|███▎                                          | 277/3893 [01:21<17:41,  3.41it/s]

  7%|███▎                                          | 278/3893 [01:21<17:41,  3.41it/s]

  7%|███▎                                          | 279/3893 [01:21<17:41,  3.41it/s]

  7%|███▎                                          | 280/3893 [01:22<17:40,  3.41it/s]

  7%|███▎                                          | 281/3893 [01:22<17:40,  3.41it/s]

  7%|███▎                                          | 282/3893 [01:22<17:40,  3.41it/s]

  7%|███▎                                          | 283/3893 [01:23<17:40,  3.41it/s]

  7%|███▎                                          | 284/3893 [01:23<17:39,  3.40it/s]

  7%|███▎                                          | 285/3893 [01:23<17:39,  3.40it/s]

  7%|███▍                                          | 286/3893 [01:23<17:39,  3.40it/s]

  7%|███▍                                          | 287/3893 [01:24<17:38,  3.41it/s]

  7%|███▍                                          | 288/3893 [01:24<17:38,  3.41it/s]

  7%|███▍                                          | 289/3893 [01:24<17:38,  3.41it/s]

  7%|███▍                                          | 290/3893 [01:25<17:38,  3.41it/s]

  7%|███▍                                          | 291/3893 [01:25<17:37,  3.41it/s]

  8%|███▍                                          | 292/3893 [01:25<17:37,  3.41it/s]

  8%|███▍                                          | 293/3893 [01:26<17:37,  3.40it/s]

  8%|███▍                                          | 294/3893 [01:26<17:36,  3.41it/s]

  8%|███▍                                          | 295/3893 [01:26<17:36,  3.41it/s]

  8%|███▍                                          | 296/3893 [01:26<17:36,  3.41it/s]

  8%|███▌                                          | 297/3893 [01:27<17:35,  3.41it/s]

  8%|███▌                                          | 298/3893 [01:27<17:35,  3.41it/s]

  8%|███▌                                          | 299/3893 [01:27<17:35,  3.41it/s]

  8%|███▌                                          | 300/3893 [01:28<17:35,  3.41it/s]

  8%|███▌                                          | 301/3893 [01:28<17:34,  3.41it/s]

  8%|███▌                                          | 302/3893 [01:28<17:34,  3.40it/s]

  8%|███▌                                          | 303/3893 [01:28<17:34,  3.40it/s]

  8%|███▌                                          | 304/3893 [01:29<17:34,  3.40it/s]

  8%|███▌                                          | 305/3893 [01:29<17:33,  3.40it/s]

  8%|███▌                                          | 306/3893 [01:29<17:33,  3.40it/s]

  8%|███▋                                          | 307/3893 [01:30<17:32,  3.41it/s]

  8%|███▋                                          | 308/3893 [01:30<17:32,  3.41it/s]

  8%|███▋                                          | 309/3893 [01:30<17:32,  3.41it/s]

  8%|███▋                                          | 310/3893 [01:31<17:31,  3.41it/s]

  8%|███▋                                          | 311/3893 [01:31<17:31,  3.41it/s]

  8%|███▋                                          | 312/3893 [01:31<17:31,  3.41it/s]

  8%|███▋                                          | 313/3893 [01:31<17:31,  3.41it/s]

  8%|███▋                                          | 314/3893 [01:32<17:30,  3.41it/s]

  8%|███▋                                          | 315/3893 [01:32<17:30,  3.41it/s]

  8%|███▋                                          | 316/3893 [01:32<17:30,  3.41it/s]

  8%|███▋                                          | 317/3893 [01:33<17:29,  3.41it/s]

  8%|███▊                                          | 318/3893 [01:33<17:29,  3.41it/s]

  8%|███▊                                          | 319/3893 [01:33<17:29,  3.41it/s]

  8%|███▊                                          | 320/3893 [01:33<17:28,  3.41it/s]

  8%|███▊                                          | 321/3893 [01:34<17:28,  3.41it/s]

  8%|███▊                                          | 322/3893 [01:34<17:28,  3.41it/s]

  8%|███▊                                          | 323/3893 [01:34<17:28,  3.41it/s]

  8%|███▊                                          | 324/3893 [01:35<17:28,  3.41it/s]

  8%|███▊                                          | 325/3893 [01:35<17:27,  3.40it/s]

  8%|███▊                                          | 326/3893 [01:35<17:27,  3.40it/s]

  8%|███▊                                          | 327/3893 [01:36<17:27,  3.40it/s]

  8%|███▉                                          | 328/3893 [01:36<17:27,  3.40it/s]

  8%|███▉                                          | 329/3893 [01:36<17:26,  3.41it/s]

  8%|███▉                                          | 330/3893 [01:36<17:26,  3.41it/s]

  9%|███▉                                          | 331/3893 [01:37<17:25,  3.41it/s]

  9%|███▉                                          | 332/3893 [01:37<17:25,  3.41it/s]

  9%|███▉                                          | 333/3893 [01:37<17:25,  3.41it/s]

  9%|███▉                                          | 334/3893 [01:38<17:24,  3.41it/s]

  9%|███▉                                          | 335/3893 [01:38<17:24,  3.41it/s]

  9%|███▉                                          | 336/3893 [01:38<17:24,  3.41it/s]

  9%|███▉                                          | 337/3893 [01:38<17:23,  3.41it/s]

  9%|███▉                                          | 338/3893 [01:39<17:23,  3.41it/s]

  9%|████                                          | 339/3893 [01:39<17:23,  3.41it/s]

  9%|████                                          | 340/3893 [01:39<17:23,  3.40it/s]

  9%|████                                          | 341/3893 [01:40<17:23,  3.40it/s]

  9%|████                                          | 342/3893 [01:40<17:23,  3.40it/s]

  9%|████                                          | 343/3893 [01:40<17:22,  3.40it/s]

  9%|████                                          | 344/3893 [01:41<17:23,  3.40it/s]

  9%|████                                          | 345/3893 [01:41<17:22,  3.40it/s]

  9%|████                                          | 346/3893 [01:41<17:22,  3.40it/s]

  9%|████                                          | 347/3893 [01:41<17:22,  3.40it/s]

  9%|████                                          | 348/3893 [01:42<17:21,  3.40it/s]

  9%|████                                          | 349/3893 [01:42<17:21,  3.40it/s]

  9%|████▏                                         | 350/3893 [01:42<17:21,  3.40it/s]

  9%|████▏                                         | 351/3893 [01:43<17:20,  3.40it/s]

  9%|████▏                                         | 352/3893 [01:43<17:20,  3.40it/s]

  9%|████▏                                         | 353/3893 [01:43<17:20,  3.40it/s]

  9%|████▏                                         | 354/3893 [01:43<17:20,  3.40it/s]

  9%|████▏                                         | 355/3893 [01:44<17:19,  3.40it/s]

  9%|████▏                                         | 356/3893 [01:44<17:19,  3.40it/s]

  9%|████▏                                         | 357/3893 [01:44<17:19,  3.40it/s]

  9%|████▏                                         | 358/3893 [01:45<17:18,  3.40it/s]

  9%|████▏                                         | 359/3893 [01:45<17:18,  3.40it/s]

  9%|████▎                                         | 360/3893 [01:45<17:17,  3.40it/s]

  9%|████▎                                         | 361/3893 [01:46<17:17,  3.40it/s]

  9%|████▎                                         | 362/3893 [01:46<17:17,  3.40it/s]

  9%|████▎                                         | 363/3893 [01:46<17:16,  3.40it/s]

  9%|████▎                                         | 364/3893 [01:46<17:16,  3.40it/s]

  9%|████▎                                         | 365/3893 [01:47<17:16,  3.40it/s]

  9%|████▎                                         | 366/3893 [01:47<17:15,  3.40it/s]

  9%|████▎                                         | 367/3893 [01:47<17:15,  3.40it/s]

  9%|████▎                                         | 368/3893 [01:48<17:15,  3.41it/s]

  9%|████▎                                         | 369/3893 [01:48<17:14,  3.41it/s]

 10%|████▎                                         | 370/3893 [01:48<17:14,  3.41it/s]

 10%|████▍                                         | 371/3893 [01:48<17:13,  3.41it/s]

 10%|████▍                                         | 372/3893 [01:49<17:13,  3.41it/s]

 10%|████▍                                         | 373/3893 [01:49<17:13,  3.41it/s]

 10%|████▍                                         | 374/3893 [01:49<17:13,  3.41it/s]

 10%|████▍                                         | 375/3893 [01:50<17:13,  3.41it/s]

 10%|████▍                                         | 376/3893 [01:50<17:12,  3.40it/s]

 10%|████▍                                         | 377/3893 [01:50<17:12,  3.41it/s]

 10%|████▍                                         | 378/3893 [01:51<17:11,  3.41it/s]

 10%|████▍                                         | 379/3893 [01:51<17:11,  3.41it/s]

 10%|████▍                                         | 380/3893 [01:51<17:11,  3.41it/s]

 10%|████▌                                         | 381/3893 [01:51<17:11,  3.40it/s]

 10%|████▌                                         | 382/3893 [01:52<17:11,  3.40it/s]

 10%|████▌                                         | 383/3893 [01:52<17:11,  3.40it/s]

 10%|████▌                                         | 384/3893 [01:52<17:11,  3.40it/s]

 10%|████▌                                         | 385/3893 [01:53<17:10,  3.40it/s]

 10%|████▌                                         | 386/3893 [01:53<17:10,  3.40it/s]

 10%|████▌                                         | 387/3893 [01:53<17:09,  3.40it/s]

 10%|████▌                                         | 388/3893 [01:53<17:09,  3.41it/s]

 10%|████▌                                         | 389/3893 [01:54<17:09,  3.40it/s]

 10%|████▌                                         | 390/3893 [01:54<17:08,  3.41it/s]

 10%|████▌                                         | 391/3893 [01:54<17:08,  3.41it/s]

 10%|████▋                                         | 392/3893 [01:55<17:07,  3.41it/s]

 10%|████▋                                         | 393/3893 [01:55<17:07,  3.41it/s]

 10%|████▋                                         | 394/3893 [01:55<17:07,  3.41it/s]

 10%|████▋                                         | 395/3893 [01:56<17:07,  3.41it/s]

 10%|████▋                                         | 396/3893 [01:56<17:07,  3.40it/s]

 10%|████▋                                         | 397/3893 [01:56<17:06,  3.41it/s]

 10%|████▋                                         | 398/3893 [01:56<17:06,  3.40it/s]

 10%|████▋                                         | 399/3893 [01:57<17:06,  3.40it/s]

 10%|████▋                                         | 400/3893 [01:57<17:05,  3.41it/s]

 10%|████▋                                         | 401/3893 [01:57<17:05,  3.40it/s]

 10%|████▊                                         | 402/3893 [01:58<17:05,  3.40it/s]

 10%|████▊                                         | 403/3893 [01:58<17:04,  3.41it/s]

 10%|████▊                                         | 404/3893 [01:58<17:04,  3.40it/s]

 10%|████▊                                         | 405/3893 [01:58<17:04,  3.40it/s]

 10%|████▊                                         | 406/3893 [01:59<17:04,  3.40it/s]

 10%|████▊                                         | 407/3893 [01:59<17:03,  3.40it/s]

 10%|████▊                                         | 408/3893 [01:59<17:03,  3.40it/s]

 11%|████▊                                         | 409/3893 [02:00<17:03,  3.40it/s]

 11%|████▊                                         | 410/3893 [02:00<17:02,  3.40it/s]

 11%|████▊                                         | 411/3893 [02:00<17:02,  3.40it/s]

 11%|████▊                                         | 412/3893 [02:00<17:02,  3.40it/s]

 11%|████▉                                         | 413/3893 [02:01<17:01,  3.41it/s]

 11%|████▉                                         | 414/3893 [02:01<17:01,  3.41it/s]

 11%|████▉                                         | 415/3893 [02:01<17:01,  3.40it/s]

 11%|████▉                                         | 416/3893 [02:02<17:01,  3.41it/s]

 11%|████▉                                         | 417/3893 [02:02<17:00,  3.41it/s]

 11%|████▉                                         | 418/3893 [02:02<17:00,  3.41it/s]

 11%|████▉                                         | 419/3893 [02:03<17:00,  3.41it/s]

 11%|████▉                                         | 420/3893 [02:03<17:00,  3.40it/s]

 11%|████▉                                         | 421/3893 [02:03<16:59,  3.40it/s]

 11%|████▉                                         | 422/3893 [02:03<16:59,  3.40it/s]

 11%|████▉                                         | 423/3893 [02:04<16:59,  3.40it/s]

 11%|█████                                         | 424/3893 [02:04<16:59,  3.40it/s]

 11%|█████                                         | 425/3893 [02:04<16:58,  3.40it/s]

 11%|█████                                         | 426/3893 [02:05<16:58,  3.40it/s]

 11%|█████                                         | 427/3893 [02:05<16:58,  3.40it/s]

 11%|█████                                         | 428/3893 [02:05<16:58,  3.40it/s]

 11%|█████                                         | 429/3893 [02:05<16:58,  3.40it/s]

 11%|█████                                         | 430/3893 [02:06<16:57,  3.40it/s]

 11%|█████                                         | 431/3893 [02:06<16:57,  3.40it/s]

 11%|█████                                         | 432/3893 [02:06<16:57,  3.40it/s]

 11%|█████                                         | 433/3893 [02:07<16:56,  3.40it/s]

 11%|█████▏                                        | 434/3893 [02:07<16:56,  3.40it/s]

 11%|█████▏                                        | 435/3893 [02:07<16:55,  3.40it/s]

 11%|█████▏                                        | 436/3893 [02:08<16:55,  3.40it/s]

 11%|█████▏                                        | 437/3893 [02:08<16:55,  3.40it/s]

 11%|█████▏                                        | 438/3893 [02:08<16:54,  3.40it/s]

 11%|█████▏                                        | 439/3893 [02:08<16:54,  3.41it/s]

 11%|█████▏                                        | 440/3893 [02:09<16:53,  3.41it/s]

 11%|█████▏                                        | 441/3893 [02:09<16:53,  3.41it/s]

 11%|█████▏                                        | 442/3893 [02:09<16:53,  3.41it/s]

 11%|█████▏                                        | 443/3893 [02:10<16:52,  3.41it/s]

 11%|█████▏                                        | 444/3893 [02:10<16:52,  3.41it/s]

 11%|█████▎                                        | 445/3893 [02:10<16:52,  3.41it/s]

 11%|█████▎                                        | 446/3893 [02:10<16:51,  3.41it/s]

 11%|█████▎                                        | 447/3893 [02:11<16:51,  3.41it/s]

 12%|█████▎                                        | 448/3893 [02:11<16:51,  3.41it/s]

 12%|█████▎                                        | 449/3893 [02:11<16:51,  3.41it/s]

 12%|█████▎                                        | 450/3893 [02:12<16:51,  3.40it/s]

 12%|█████▎                                        | 451/3893 [02:12<16:51,  3.40it/s]

 12%|█████▎                                        | 452/3893 [02:12<16:53,  3.40it/s]

 12%|█████▎                                        | 453/3893 [02:13<16:52,  3.40it/s]

 12%|█████▎                                        | 454/3893 [02:13<16:51,  3.40it/s]

 12%|█████▍                                        | 455/3893 [02:13<16:50,  3.40it/s]

 12%|█████▍                                        | 456/3893 [02:13<16:49,  3.40it/s]

 12%|█████▍                                        | 457/3893 [02:14<16:49,  3.40it/s]

 12%|█████▍                                        | 458/3893 [02:14<16:49,  3.40it/s]

 12%|█████▍                                        | 459/3893 [02:14<16:48,  3.40it/s]

 12%|█████▍                                        | 460/3893 [02:15<16:48,  3.41it/s]

 12%|█████▍                                        | 461/3893 [02:15<16:47,  3.41it/s]

 12%|█████▍                                        | 462/3893 [02:15<16:47,  3.41it/s]

 12%|█████▍                                        | 463/3893 [02:15<16:46,  3.41it/s]

 12%|█████▍                                        | 464/3893 [02:16<16:46,  3.41it/s]

 12%|█████▍                                        | 465/3893 [02:16<16:46,  3.41it/s]

 12%|█████▌                                        | 466/3893 [02:16<16:46,  3.41it/s]

 12%|█████▌                                        | 467/3893 [02:17<16:46,  3.41it/s]

 12%|█████▌                                        | 468/3893 [02:17<16:45,  3.41it/s]

 12%|█████▌                                        | 469/3893 [02:17<16:45,  3.41it/s]

 12%|█████▌                                        | 470/3893 [02:18<16:44,  3.41it/s]

 12%|█████▌                                        | 471/3893 [02:18<16:44,  3.41it/s]

 12%|█████▌                                        | 472/3893 [02:18<16:44,  3.41it/s]

 12%|█████▌                                        | 473/3893 [02:18<16:44,  3.41it/s]

 12%|█████▌                                        | 474/3893 [02:19<16:44,  3.41it/s]

 12%|█████▌                                        | 475/3893 [02:19<16:43,  3.41it/s]

 12%|█████▌                                        | 476/3893 [02:19<16:43,  3.40it/s]

 12%|█████▋                                        | 477/3893 [02:20<16:43,  3.40it/s]

 12%|█████▋                                        | 478/3893 [02:20<16:42,  3.41it/s]

 12%|█████▋                                        | 479/3893 [02:20<16:42,  3.41it/s]

 12%|█████▋                                        | 480/3893 [02:20<16:42,  3.41it/s]

 12%|█████▋                                        | 481/3893 [02:21<16:41,  3.41it/s]

 12%|█████▋                                        | 482/3893 [02:21<16:41,  3.41it/s]

 12%|█████▋                                        | 483/3893 [02:21<16:41,  3.41it/s]

 12%|█████▋                                        | 484/3893 [02:22<16:40,  3.41it/s]

 12%|█████▋                                        | 485/3893 [02:22<16:40,  3.41it/s]

 12%|█████▋                                        | 486/3893 [02:22<16:40,  3.41it/s]

 13%|█████▊                                        | 487/3893 [02:23<16:39,  3.41it/s]

 13%|█████▊                                        | 488/3893 [02:23<16:39,  3.41it/s]

 13%|█████▊                                        | 489/3893 [02:23<16:39,  3.41it/s]

 13%|█████▊                                        | 490/3893 [02:23<16:38,  3.41it/s]

 13%|█████▊                                        | 491/3893 [02:24<16:38,  3.41it/s]

 13%|█████▊                                        | 492/3893 [02:24<16:38,  3.41it/s]

 13%|█████▊                                        | 493/3893 [02:24<16:38,  3.40it/s]

 13%|█████▊                                        | 494/3893 [02:25<16:38,  3.40it/s]

 13%|█████▊                                        | 495/3893 [02:25<16:38,  3.40it/s]

 13%|█████▊                                        | 496/3893 [02:25<16:38,  3.40it/s]

 13%|█████▊                                        | 497/3893 [02:25<16:38,  3.40it/s]

 13%|█████▉                                        | 498/3893 [02:26<16:37,  3.40it/s]

 13%|█████▉                                        | 499/3893 [02:26<16:37,  3.40it/s]

 13%|█████▉                                        | 500/3893 [02:26<16:36,  3.40it/s]

 13%|█████▉                                        | 501/3893 [02:27<16:36,  3.40it/s]

 13%|█████▉                                        | 502/3893 [02:27<16:36,  3.40it/s]

 13%|█████▉                                        | 503/3893 [02:27<16:36,  3.40it/s]

 13%|█████▉                                        | 504/3893 [02:28<16:35,  3.40it/s]

 13%|█████▉                                        | 505/3893 [02:28<16:35,  3.40it/s]

 13%|█████▉                                        | 506/3893 [02:28<16:35,  3.40it/s]

 13%|█████▉                                        | 507/3893 [02:28<16:34,  3.40it/s]

 13%|██████                                        | 508/3893 [02:29<16:34,  3.40it/s]

 13%|██████                                        | 509/3893 [02:29<16:34,  3.40it/s]

 13%|██████                                        | 510/3893 [02:29<16:33,  3.40it/s]

 13%|██████                                        | 511/3893 [02:30<16:33,  3.40it/s]

 13%|██████                                        | 512/3893 [02:30<16:33,  3.40it/s]

 13%|██████                                        | 513/3893 [02:30<16:33,  3.40it/s]

 13%|██████                                        | 514/3893 [02:30<16:32,  3.40it/s]

 13%|██████                                        | 515/3893 [02:31<16:32,  3.40it/s]

 13%|██████                                        | 516/3893 [02:31<16:32,  3.40it/s]

 13%|██████                                        | 517/3893 [02:31<16:31,  3.40it/s]

 13%|██████                                        | 518/3893 [02:32<16:31,  3.40it/s]

 13%|██████▏                                       | 519/3893 [02:32<16:30,  3.40it/s]

 13%|██████▏                                       | 520/3893 [02:32<16:30,  3.41it/s]

 13%|██████▏                                       | 521/3893 [02:33<16:30,  3.41it/s]

 13%|██████▏                                       | 522/3893 [02:33<16:29,  3.41it/s]

 13%|██████▏                                       | 523/3893 [02:33<16:29,  3.41it/s]

 13%|██████▏                                       | 524/3893 [02:33<16:29,  3.40it/s]

 13%|██████▏                                       | 525/3893 [02:34<16:29,  3.40it/s]

 14%|██████▏                                       | 526/3893 [02:34<16:29,  3.40it/s]

 14%|██████▏                                       | 527/3893 [02:34<16:28,  3.40it/s]

 14%|██████▏                                       | 528/3893 [02:35<16:28,  3.40it/s]

 14%|██████▎                                       | 529/3893 [02:35<16:28,  3.40it/s]

 14%|██████▎                                       | 530/3893 [02:35<16:28,  3.40it/s]

 14%|██████▎                                       | 531/3893 [02:35<16:28,  3.40it/s]

 14%|██████▎                                       | 532/3893 [02:36<16:27,  3.40it/s]

 14%|██████▎                                       | 533/3893 [02:36<16:27,  3.40it/s]

 14%|██████▎                                       | 534/3893 [02:36<16:27,  3.40it/s]

 14%|██████▎                                       | 535/3893 [02:37<16:27,  3.40it/s]

 14%|██████▎                                       | 536/3893 [02:37<16:26,  3.40it/s]

 14%|██████▎                                       | 537/3893 [02:37<16:26,  3.40it/s]

 14%|██████▎                                       | 538/3893 [02:38<16:25,  3.40it/s]

 14%|██████▎                                       | 539/3893 [02:38<16:25,  3.40it/s]

 14%|██████▍                                       | 540/3893 [02:38<16:24,  3.40it/s]

 14%|██████▍                                       | 541/3893 [02:38<16:24,  3.40it/s]

 14%|██████▍                                       | 542/3893 [02:39<16:24,  3.40it/s]

 14%|██████▍                                       | 543/3893 [02:39<16:23,  3.40it/s]

 14%|██████▍                                       | 544/3893 [02:39<16:23,  3.41it/s]

 14%|██████▍                                       | 545/3893 [02:40<16:23,  3.41it/s]

 14%|██████▍                                       | 546/3893 [02:40<16:22,  3.41it/s]

 14%|██████▍                                       | 547/3893 [02:40<16:22,  3.40it/s]

 14%|██████▍                                       | 548/3893 [02:40<16:22,  3.40it/s]

 14%|██████▍                                       | 549/3893 [02:41<16:21,  3.41it/s]

 14%|██████▍                                       | 550/3893 [02:41<16:21,  3.40it/s]

 14%|██████▌                                       | 551/3893 [02:41<16:21,  3.40it/s]

 14%|██████▌                                       | 552/3893 [02:42<16:21,  3.41it/s]

 14%|██████▌                                       | 553/3893 [02:42<16:20,  3.41it/s]

 14%|██████▌                                       | 554/3893 [02:42<16:20,  3.40it/s]

 14%|██████▌                                       | 555/3893 [02:43<16:20,  3.40it/s]

 14%|██████▌                                       | 556/3893 [02:43<16:20,  3.40it/s]

 14%|██████▌                                       | 557/3893 [02:43<16:20,  3.40it/s]

 14%|██████▌                                       | 558/3893 [02:43<16:20,  3.40it/s]

 14%|██████▌                                       | 559/3893 [02:44<16:19,  3.40it/s]

 14%|██████▌                                       | 560/3893 [02:44<16:19,  3.40it/s]

 14%|██████▋                                       | 561/3893 [02:44<16:19,  3.40it/s]

 14%|██████▋                                       | 562/3893 [02:45<16:19,  3.40it/s]

 14%|██████▋                                       | 563/3893 [02:45<16:18,  3.40it/s]

 14%|██████▋                                       | 564/3893 [02:45<16:18,  3.40it/s]

 15%|██████▋                                       | 565/3893 [02:45<16:18,  3.40it/s]

 15%|██████▋                                       | 566/3893 [02:46<16:18,  3.40it/s]

 15%|██████▋                                       | 567/3893 [02:46<16:18,  3.40it/s]

 15%|██████▋                                       | 568/3893 [02:46<16:17,  3.40it/s]

 15%|██████▋                                       | 569/3893 [02:47<16:17,  3.40it/s]

 15%|██████▋                                       | 570/3893 [02:47<16:16,  3.40it/s]

 15%|██████▋                                       | 571/3893 [02:47<16:16,  3.40it/s]

 15%|██████▊                                       | 572/3893 [02:47<16:15,  3.40it/s]

 15%|██████▊                                       | 573/3893 [02:48<16:15,  3.40it/s]

 15%|██████▊                                       | 574/3893 [02:48<16:15,  3.40it/s]

 15%|██████▊                                       | 575/3893 [02:48<16:15,  3.40it/s]

 15%|██████▊                                       | 576/3893 [02:49<16:14,  3.40it/s]

 15%|██████▊                                       | 577/3893 [02:49<16:14,  3.40it/s]

 15%|██████▊                                       | 578/3893 [02:49<16:14,  3.40it/s]

 15%|██████▊                                       | 579/3893 [02:50<16:14,  3.40it/s]

 15%|██████▊                                       | 580/3893 [02:50<16:13,  3.40it/s]

 15%|██████▊                                       | 581/3893 [02:50<16:13,  3.40it/s]

 15%|██████▉                                       | 582/3893 [02:50<16:13,  3.40it/s]

 15%|██████▉                                       | 583/3893 [02:51<16:12,  3.40it/s]

 15%|██████▉                                       | 584/3893 [02:51<16:12,  3.40it/s]

 15%|██████▉                                       | 585/3893 [02:51<16:11,  3.40it/s]

 15%|██████▉                                       | 586/3893 [02:52<16:11,  3.40it/s]

 15%|██████▉                                       | 587/3893 [02:52<16:11,  3.40it/s]

 15%|██████▉                                       | 588/3893 [02:52<16:10,  3.40it/s]

 15%|██████▉                                       | 589/3893 [02:52<16:10,  3.40it/s]

 15%|██████▉                                       | 590/3893 [02:53<16:10,  3.40it/s]

 15%|██████▉                                       | 591/3893 [02:53<16:09,  3.40it/s]

 15%|██████▉                                       | 592/3893 [02:53<16:09,  3.41it/s]

 15%|███████                                       | 593/3893 [02:54<16:09,  3.41it/s]

 15%|███████                                       | 594/3893 [02:54<16:08,  3.41it/s]

 15%|███████                                       | 595/3893 [02:54<16:08,  3.41it/s]

 15%|███████                                       | 596/3893 [02:55<16:07,  3.41it/s]

 15%|███████                                       | 597/3893 [02:55<16:07,  3.41it/s]

 15%|███████                                       | 598/3893 [02:55<16:07,  3.40it/s]

 15%|███████                                       | 599/3893 [02:55<16:07,  3.40it/s]

 15%|███████                                       | 600/3893 [02:56<16:07,  3.40it/s]

 15%|███████                                       | 601/3893 [02:56<16:07,  3.40it/s]

 15%|███████                                       | 602/3893 [02:56<16:06,  3.40it/s]

 15%|███████▏                                      | 603/3893 [02:57<16:06,  3.40it/s]

 16%|███████▏                                      | 604/3893 [02:57<16:06,  3.40it/s]

 16%|███████▏                                      | 605/3893 [02:57<16:05,  3.41it/s]

 16%|███████▏                                      | 606/3893 [02:57<16:05,  3.41it/s]

 16%|███████▏                                      | 607/3893 [02:58<16:04,  3.41it/s]

 16%|███████▏                                      | 608/3893 [02:58<16:04,  3.41it/s]

 16%|███████▏                                      | 609/3893 [02:58<16:04,  3.41it/s]

 16%|███████▏                                      | 610/3893 [02:59<16:03,  3.41it/s]

 16%|███████▏                                      | 611/3893 [02:59<16:03,  3.41it/s]

 16%|███████▏                                      | 612/3893 [02:59<16:03,  3.41it/s]

 16%|███████▏                                      | 613/3893 [03:00<16:03,  3.41it/s]

 16%|███████▎                                      | 614/3893 [03:00<16:02,  3.41it/s]

 16%|███████▎                                      | 615/3893 [03:00<16:02,  3.41it/s]

 16%|███████▎                                      | 616/3893 [03:00<16:02,  3.41it/s]

 16%|███████▎                                      | 617/3893 [03:01<16:01,  3.41it/s]

 16%|███████▎                                      | 618/3893 [03:01<16:01,  3.41it/s]

 16%|███████▎                                      | 619/3893 [03:01<16:01,  3.40it/s]

 16%|███████▎                                      | 620/3893 [03:02<16:01,  3.40it/s]

 16%|███████▎                                      | 621/3893 [03:02<16:00,  3.40it/s]

 16%|███████▎                                      | 622/3893 [03:02<16:00,  3.40it/s]

 16%|███████▎                                      | 623/3893 [03:02<16:00,  3.40it/s]

 16%|███████▎                                      | 624/3893 [03:03<16:00,  3.41it/s]

 16%|███████▍                                      | 625/3893 [03:03<16:00,  3.40it/s]

 16%|███████▍                                      | 626/3893 [03:03<16:00,  3.40it/s]

 16%|███████▍                                      | 627/3893 [03:04<15:59,  3.40it/s]

 16%|███████▍                                      | 628/3893 [03:04<15:58,  3.40it/s]

 16%|███████▍                                      | 629/3893 [03:04<15:58,  3.41it/s]

 16%|███████▍                                      | 630/3893 [03:05<15:58,  3.41it/s]

 16%|███████▍                                      | 631/3893 [03:05<15:58,  3.40it/s]

 16%|███████▍                                      | 632/3893 [03:05<15:57,  3.41it/s]

 16%|███████▍                                      | 633/3893 [03:05<15:57,  3.41it/s]

 16%|███████▍                                      | 634/3893 [03:06<15:57,  3.41it/s]

 16%|███████▌                                      | 635/3893 [03:06<15:56,  3.41it/s]

 16%|███████▌                                      | 636/3893 [03:06<15:56,  3.40it/s]

 16%|███████▌                                      | 637/3893 [03:07<15:56,  3.40it/s]

 16%|███████▌                                      | 638/3893 [03:07<15:56,  3.40it/s]

 16%|███████▌                                      | 639/3893 [03:07<15:56,  3.40it/s]

 16%|███████▌                                      | 640/3893 [03:07<15:55,  3.40it/s]

 16%|███████▌                                      | 641/3893 [03:08<15:55,  3.40it/s]

 16%|███████▌                                      | 642/3893 [03:08<15:55,  3.40it/s]

 17%|███████▌                                      | 643/3893 [03:08<15:54,  3.40it/s]

 17%|███████▌                                      | 644/3893 [03:09<15:54,  3.40it/s]

 17%|███████▌                                      | 645/3893 [03:09<15:54,  3.40it/s]

 17%|███████▋                                      | 646/3893 [03:09<15:53,  3.40it/s]

 17%|███████▋                                      | 647/3893 [03:10<15:52,  3.41it/s]

 17%|███████▋                                      | 648/3893 [03:10<15:52,  3.41it/s]

 17%|███████▋                                      | 649/3893 [03:10<15:52,  3.40it/s]

 17%|███████▋                                      | 650/3893 [03:10<15:52,  3.41it/s]

 17%|███████▋                                      | 651/3893 [03:11<15:52,  3.41it/s]

 17%|███████▋                                      | 652/3893 [03:11<15:51,  3.40it/s]

 17%|███████▋                                      | 653/3893 [03:11<15:51,  3.41it/s]

 17%|███████▋                                      | 654/3893 [03:12<15:51,  3.41it/s]

 17%|███████▋                                      | 655/3893 [03:12<15:50,  3.41it/s]

 17%|███████▊                                      | 656/3893 [03:12<15:50,  3.41it/s]

 17%|███████▊                                      | 657/3893 [03:12<15:50,  3.41it/s]

 17%|███████▊                                      | 658/3893 [03:13<15:50,  3.40it/s]

 17%|███████▊                                      | 659/3893 [03:13<15:49,  3.40it/s]

 17%|███████▊                                      | 660/3893 [03:13<15:49,  3.40it/s]

 17%|███████▊                                      | 661/3893 [03:14<15:49,  3.40it/s]

 17%|███████▊                                      | 662/3893 [03:14<15:49,  3.40it/s]

 17%|███████▊                                      | 663/3893 [03:14<15:48,  3.40it/s]

 17%|███████▊                                      | 664/3893 [03:15<15:48,  3.40it/s]

 17%|███████▊                                      | 665/3893 [03:15<15:48,  3.40it/s]

 17%|███████▊                                      | 666/3893 [03:15<15:47,  3.40it/s]

 17%|███████▉                                      | 667/3893 [03:15<15:47,  3.40it/s]

 17%|███████▉                                      | 668/3893 [03:16<15:47,  3.40it/s]

 17%|███████▉                                      | 669/3893 [03:16<15:46,  3.40it/s]

 17%|███████▉                                      | 670/3893 [03:16<15:46,  3.40it/s]

 17%|███████▉                                      | 671/3893 [03:17<15:46,  3.40it/s]

 17%|███████▉                                      | 672/3893 [03:17<15:46,  3.40it/s]

 17%|███████▉                                      | 673/3893 [03:17<15:45,  3.40it/s]

 17%|███████▉                                      | 674/3893 [03:17<15:46,  3.40it/s]

 17%|███████▉                                      | 675/3893 [03:18<15:46,  3.40it/s]

 17%|███████▉                                      | 676/3893 [03:18<15:45,  3.40it/s]

 17%|███████▉                                      | 677/3893 [03:18<15:45,  3.40it/s]

 17%|████████                                      | 678/3893 [03:19<15:44,  3.40it/s]

 17%|████████                                      | 679/3893 [03:19<15:43,  3.40it/s]

 17%|████████                                      | 680/3893 [03:19<15:43,  3.41it/s]

 17%|████████                                      | 681/3893 [03:20<15:43,  3.40it/s]

 18%|████████                                      | 682/3893 [03:20<15:43,  3.40it/s]

 18%|████████                                      | 683/3893 [03:20<15:43,  3.40it/s]

 18%|████████                                      | 684/3893 [03:20<15:42,  3.40it/s]

 18%|████████                                      | 685/3893 [03:21<15:42,  3.40it/s]

 18%|████████                                      | 686/3893 [03:21<15:41,  3.40it/s]

 18%|████████                                      | 687/3893 [03:21<15:41,  3.40it/s]

 18%|████████▏                                     | 688/3893 [03:22<15:41,  3.40it/s]

 18%|████████▏                                     | 689/3893 [03:22<15:41,  3.40it/s]

 18%|████████▏                                     | 690/3893 [03:22<15:40,  3.40it/s]

 18%|████████▏                                     | 691/3893 [03:22<15:40,  3.40it/s]

 18%|████████▏                                     | 692/3893 [03:23<15:39,  3.41it/s]

 18%|████████▏                                     | 693/3893 [03:23<15:39,  3.41it/s]

 18%|████████▏                                     | 694/3893 [03:23<15:39,  3.41it/s]

 18%|████████▏                                     | 695/3893 [03:24<15:38,  3.41it/s]

 18%|████████▏                                     | 696/3893 [03:24<15:38,  3.41it/s]

 18%|████████▏                                     | 697/3893 [03:24<15:38,  3.41it/s]

 18%|████████▏                                     | 698/3893 [03:25<15:37,  3.41it/s]

 18%|████████▎                                     | 699/3893 [03:25<15:37,  3.41it/s]

 18%|████████▎                                     | 700/3893 [03:25<15:37,  3.41it/s]

 18%|████████▎                                     | 700/3893 [03:25<15:39,  3.40it/s]

KeyboardInterrupt:

We calculate the change in likelihoods for each variant relative to the likelihood of their respective wild-type sequence.

In [ ]:
# Subtract score of corresponding reference sequences from scores of variant sequences
delta_scores = np.array(var_scores) - np.array(ref_scores)[ref_seq_indexes]

# Add delta scores to dataframe
brca1_df[f'evo2_delta_score'] = delta_scores

brca1_df.head(10)

This delta likelihood should be predictive of how disruptive the SNV is to the protein's function: the lower the delta, the more likely that the SNV is disruptive. We can show this by comparing the distributions of delta likelihoods for the two classes of SNVs (functional/intermediate vs loss-of-function).

In [ ]:
plt.figure(figsize=(4, 2))

# Plot stripplot of distributions
p = sns.stripplot(
    data=brca1_df,
    x='evo2_delta_score',
    y='class',
    hue='class',
    order=['FUNC/INT', 'LOF'],
    palette=['#777777', 'C3'],
    size=2,
    jitter=0.3,
)

# Mark medians from each distribution
sns.boxplot(showmeans=True,
            meanline=True,
            meanprops={'visible': False},
            medianprops={'color': 'k', 'ls': '-', 'lw': 2},
            whiskerprops={'visible': False},
            zorder=10,
            x="evo2_delta_score",
            y="class",
            data=brca1_df,
            showfliers=False,
            showbox=False,
            showcaps=False,
            ax=p)
plt.xlabel('Delta likelihood score, Evo 2')
plt.ylabel('BRCA1 SNV class')
plt.tight_layout()
plt.show()

We can also calculate the area under the receiver operating characteristic curve (AUROC) of this zero-shot prediction method.

In [ ]:
# Calculate AUROC of zero-shot predictions
y_true = (brca1_df['class'] == 'LOF')
auroc = roc_auc_score(y_true, -brca1_df['evo2_delta_score'])

print(f'Zero-shot prediction AUROC: {auroc:.2}')